/*****************************************************************************
  AUTO-GENERATED CODE:  Graphics Resource Converter version: 4.00.39 BETA

  Company:
      Microchip Technology, Inc.
 
  File Name:
     internal_resource_reference.c
 
  Summary:
      This file is generated by the Microchip's Graphics Resource Converter.
  Description:
      This file is generated by the Graphics Resource Converter containing
      resources such as images and fonts that can be used by Microchip's
      Graphics Library, which is part of the MLA.
 *****************************************************************************/

// DOM-IGNORE-BEGIN
/*****************************************************************************
  Software License Agreement

  Copyright(c) 2013 Microchip Technology Inc.  All rights reserved.
  Microchip licenses to you the right to use, modify, copy and distribute
  Software only when embedded on a Microchip microcontroller or digital
  signal controller that is integrated into your product or third party
  product (pursuant to the sublicense terms in the accompanying license
  agreement).
 
  You should refer to the license agreement accompanying this Software
  for additional information regarding your rights and obligations.
 
  SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY
  KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
  OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
  PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
  OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
  BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
  DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
  INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
  COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
  CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
  OR OTHER SIMILAR COSTS.
 *****************************************************************************/
// DOM-IGNORE-END

/*****************************************************************************
 * SECTION:  Includes
 *****************************************************************************/
#include <gfx/gfx.h>
#include <stdint.h>

/*****************************************************************************
 * SECTION:  Graphics Library Firmware Check
 *****************************************************************************/
#if(GRAPHICS_LIBRARY_VERSION != 0x0400)
#warning "It is suggested to use Graphics Library version 4.00 with this version of GRC."
#endif

/*****************************************************************************
 * SECTION:  Graphics Bitmap Padding Check
 *****************************************************************************/
#ifdef GFX_CONFIG_IMAGE_PADDING_DISABLE
#error These bitmap resources have been converted with padding of the horizontal lines, but GFX_CONFIG_IMAGE_PADDING_DISABLE is defined in system_config.h.
#endif


/*****************************************************************************
 * SECTION:  Graphics Configuration: Bitmap Check
 *****************************************************************************/

#ifdef GFX_CONFIG_IMAGE_FLASH_DISABLE
#error The GFX_CONFIG_IMAGE_FLASH_DISABLE is defined in system_config.h header file.
#endif

#ifdef GFX_CONFIG_RLE_DECODE_DISABLE
#error The GFX_CONFIG_RLE_DECODE_DISABLE is defined in system_config.h header file.
#endif

/*****************************************************************************
 * SECTION:  Graphics Configuration: Font Check
 *****************************************************************************/

#ifdef GFX_CONFIG_FONT_FLASH_DISABLE
#error The GFX_CONFIG_FONT_FLASH_DISABLE is defined in system_config.h header file.
#endif


/*****************************************************************************
 * SECTION:  GOLSmallFont - Phrases
 *****************************************************************************/

const GFX_XCHAR cOnBulbStr[] = {   0x0090, 0x0000    };    //On				

const GFX_XCHAR cOffBulbStr[] = {   0x0080, 0x0000    };    //Off				

const GFX_XCHAR cSelectionStr[] = {   0x00B6, 0x0093, 0x0000    };    //Selection		

const GFX_XCHAR cAlignmentStr[] = {   0x008D, 0x00BA, 0x0000    };    //Alignment		

const GFX_XCHAR cReturnStr[] = {   0x00B4, 0x0088, 0x0000    };    //return (like the return key of the keyboard)  

const GFX_XCHAR cMeter1Str[] = {   0x007D, 0x00AB, 0x0031, 0x0000    };    //Meter1			

const GFX_XCHAR cMeter2Str[] = {   0x007D, 0x00AB, 0x0032, 0x0000    };    //Meter2			

const GFX_XCHAR cValueLabelStr[] = {   0x00AE, 0x0097, 0x0000    };    // Value (like a number value, a reading from a meter or a gauge)   

const GFX_XCHAR cMoreStr[] = {   0x009A, 0x008B, 0x007B, 0x0000    };    //MORE......     (more menu or data list)					

const GFX_XCHAR cBackStr[] = {   0x00B4, 0x0088, 0x007B, 0x0000    };    //BACK......     (back to previous menu or data list)		

const GFX_XCHAR cGroup1Str[] = {   0x00A6, 0x0031, 0x0020, 0x0000    };    //Group 1							

const GFX_XCHAR cGroup2Str[] = {   0x00A6, 0x0032, 0x0000    };    //Group 2						    

const GFX_XCHAR cSetTimeDateStr[] = {   0x00AD, 0x00A9, 0x0099, 0x00B9, 0x0087, 0x0098, 0x009B, 0x0000    };    //Set time and Date               

const GFX_XCHAR cNormalLoadStr[] = {   0x009F, 0x008E, 0x00AF, 0x00B1, 0x0000    };    //Normal Load                     

const GFX_XCHAR cLightLoadStr[] = {   0x00B2, 0x00B0, 0x00AF, 0x00B1, 0x0000    };    //Light Load                      

const GFX_XCHAR cHeavyLoadStr[] = {   0x00B2, 0x00B7, 0x00AF, 0x00B1, 0x0000    };    //Heavy Load                      

const GFX_XCHAR cUseR6PotStr[] = {   0x007F, 0x00A2, 0x0052, 0x0036, 0x00A3, 0x007E, 0x00AC, 0x0000    };    //Using R6 Potentiometer (R6 is a resistor code) 

const GFX_XCHAR cScanModeStr[] = {   0x0092, 0x0096, 0x009E, 0x0091, 0x0000    };    //Scan Mode                       

const GFX_XCHAR cScrSelList1[] = {   0x0094, 0x00B8, 0x000A,
                                    0x008A, 0x00B6, 0x009D, 0x000A,
                                    0x0084, 0x00B6, 0x0094, 0x00B8, 0x000A,
                                    0x00A6, 0x0085, 0x009D, 0x000A,
                                    0x00A0, 0x0083, 0x009C, 0x000A,
                                    0x00B5, 0x008F, 0x009C, 0x000A,
                                    0x0081, 0x00AB, 0x009D, 0x000A,
                                    0x00A8, 0x00B3, 0x009D, 0x000A,
                                    0x009A, 0x008B, 0x007B, 0x0000    };    //ScreenItems1

const GFX_XCHAR cScrSelList2[] = {   0x00B4, 0x0088, 0x007B, 0x000A,
                                    0x007D, 0x00AB, 0x000A,
                                    0x007D, 0x00AB, 0x00A4, 0x000A,
                                    0x0089, 0x00A1, 0x000A,
                                    0x00AA, 0x008C, 0x007C, 0x0095, 0x0082, 0x000A,
                                    0x00A5, 0x0086, 0x000A,
                                    0x00A7, 0x0089, 0x000A,
                                    0x0045, 0x0043, 0x0047, 0x0000    };    //Screen Items2 

const GFX_XCHAR cScrSelListLang[] = {   0x0045, 0x006E, 0x0067, 0x006C, 0x0069, 0x0073, 0x0068, 0x000A,
                                       0x0043, 0x0068, 0x0069, 0x006E, 0x0065, 0x0073, 0x0065, 0x0000    };    // "English"/"Chinese" List

const GFX_XCHAR cLanguage[] = {   0x004C, 0x0061, 0x006E, 0x0067, 0x0075, 0x0061, 0x0067, 0x0065, 0x0000    };    // "Language" string

const GFX_XCHAR eOnBulbStr[] = {   0x004F, 0x006E, 0x0000    };    // "On" string

const GFX_XCHAR eOffBulbStr[] = {   0x004F, 0x0066, 0x0066, 0x0000    };    // "Off" string

const GFX_XCHAR eSelectionStr[] = {   0x0053, 0x0065, 0x006C, 0x0065, 0x0063, 0x0074, 0x0069, 0x006F, 0x006E, 0x0000    };    // "Selection" string

const GFX_XCHAR eAlignmentStr[] = {   0x0041, 0x006C, 0x0069, 0x0067, 0x006E, 0x006D, 0x0065, 0x006E, 0x0074, 0x0000    };    // "Alignment" string 

const GFX_XCHAR eReturnStr[] = {   0x004F, 0x004B, 0x0000    };    // "OK string

const GFX_XCHAR eMeter1Str[] = {   0x004D, 0x0065, 0x0074, 0x0065, 0x0072, 0x0031, 0x0000    };    // "Meter1" string

const GFX_XCHAR eMeter2Str[] = {   0x004D, 0x0065, 0x0074, 0x0065, 0x0072, 0x0032, 0x0000    };    // "Meter2" string 

const GFX_XCHAR eValueLabelStr[] = {   0x0056, 0x0061, 0x006C, 0x0075, 0x0065, 0x0000    };    // "Value" string

const GFX_XCHAR eMoreStr[] = {   0x004D, 0x004F, 0x0052, 0x0045, 0x002E, 0x002E, 0x002E, 0x0000    };    // "MORE...." string

const GFX_XCHAR eBackStr[] = {   0x0042, 0x0041, 0x0043, 0x004B, 0x002E, 0x002E, 0x002E, 0x0000    };    // "BACK...." string

const GFX_XCHAR eGroup1Str[] = {   0x0047, 0x0072, 0x006F, 0x0075, 0x0070, 0x0020, 0x0031, 0x0000    };    // "Group 1" string

const GFX_XCHAR eGroup2Str[] = {   0x0047, 0x0072, 0x006F, 0x0075, 0x0070, 0x0020, 0x0032, 0x0000    };    // "Group 2" string

const GFX_XCHAR eSetTimeDateStr[] = {   0x0053, 0x0065, 0x0074, 0x0020, 0x0054, 0x0069, 0x006D, 0x0065, 0x0020, 0x0061, 0x006E, 0x0064, 0x0020, 0x0044, 0x0061, 0x0074, 0x0065, 0x0000    };    // "Set time and Date" string

const GFX_XCHAR eNormalLoadStr[] = {   0x004E, 0x006F, 0x0072, 0x006D, 0x0061, 0x006C, 0x0020, 0x004C, 0x006F, 0x0061, 0x0064, 0x0000    };    // "Normal Load" string

const GFX_XCHAR eLightLoadStr[] = {   0x004C, 0x0069, 0x0067, 0x0068, 0x0074, 0x0020, 0x004C, 0x006F, 0x0061, 0x0064, 0x0000    };    // "Light Load" string

const GFX_XCHAR eHeavyLoadStr[] = {   0x0048, 0x0065, 0x0061, 0x0076, 0x0079, 0x0020, 0x004C, 0x006F, 0x0061, 0x0064, 0x0000    };    // "Heavy Load" string

const GFX_XCHAR eUseR6PotStr[] = {   0x0055, 0x0073, 0x0069, 0x006E, 0x0067, 0x0020, 0x0050, 0x006F, 0x0074, 0x0065, 0x006E, 0x0074, 0x0069, 0x006F, 0x006D, 0x0065, 0x0074, 0x0065, 0x0072, 0x0000    };    // "Using Potentiometer string

const GFX_XCHAR eScanModeStr[] = {   0x0053, 0x0063, 0x0061, 0x006E, 0x0020, 0x004D, 0x006F, 0x0064, 0x0065, 0x0000    };    // "Scan Mode" string

const GFX_XCHAR eScrSelList1[] = {   0x0042, 0x0075, 0x0074, 0x0074, 0x006F, 0x006E, 0x000A,
                                    0x0043, 0x0068, 0x0065, 0x0063, 0x006B, 0x0062, 0x006F, 0x0078, 0x000A,
                                    0x0052, 0x0061, 0x0064, 0x0069, 0x006F, 0x0020, 0x0062, 0x0075, 0x0074, 0x0074, 0x006F, 0x006E, 0x0073, 0x000A,
                                    0x0047, 0x0072, 0x006F, 0x0075, 0x0070, 0x0020, 0x0042, 0x006F, 0x0078, 0x000A,
                                    0x0053, 0x006C, 0x0069, 0x0064, 0x0065, 0x0072, 0x000A,
                                    0x0050, 0x0072, 0x006F, 0x0067, 0x0072, 0x0065, 0x0073, 0x0073, 0x0020, 0x0062, 0x0061, 0x0072, 0x000A,
                                    0x004C, 0x0069, 0x0073, 0x0074, 0x0020, 0x0062, 0x006F, 0x0078, 0x000A,
                                    0x0045, 0x0064, 0x0069, 0x0074, 0x0020, 0x0062, 0x006F, 0x0078, 0x000A,
                                    0x004D, 0x004F, 0x0052, 0x0045, 0x002E, 0x002E, 0x002E, 0x0000    };    // List 1 strings

const GFX_XCHAR eScrSelList2[] = {   0x0042, 0x0041, 0x0043, 0x004B, 0x002E, 0x002E, 0x002E, 0x000A,
                                    0x004D, 0x0065, 0x0074, 0x0065, 0x0072, 0x000A,
                                    0x0044, 0x0069, 0x0061, 0x006C, 0x000A,
                                    0x0050, 0x0069, 0x0063, 0x0074, 0x0075, 0x0072, 0x0065, 0x000A,
                                    0x0043, 0x0075, 0x0073, 0x0074, 0x006F, 0x006D, 0x0020, 0x0063, 0x006F, 0x006E, 0x0074, 0x0072, 0x006F, 0x006C, 0x000A,
                                    0x0053, 0x0069, 0x0067, 0x006E, 0x0061, 0x0074, 0x0075, 0x0072, 0x0065, 0x000A,
                                    0x0050, 0x006C, 0x006F, 0x0074, 0x0074, 0x0069, 0x006E, 0x0067, 0x000A,
                                    0x0045, 0x0043, 0x0047, 0x0000    };    // List 2 strings

const GFX_XCHAR eScrSelListLang[] = {   0x0045, 0x006E, 0x0067, 0x006C, 0x0069, 0x0073, 0x0068, 0x000A,
                                       0x0043, 0x0068, 0x0069, 0x006E, 0x0065, 0x0073, 0x0065, 0x0000    };    // "English"/"Chinese" List

const GFX_XCHAR eLanguage[] = {   0x004C, 0x0061, 0x006E, 0x0067, 0x0075, 0x0061, 0x0067, 0x0065, 0x0000    };    // "Language" string

/*****************************************************************************
 * SECTION:  GOLFontDefault - Phrases
 *****************************************************************************/

const GFX_XCHAR cTouchScreenStr[] = {   0x00DE, 0x00DA, 0x00B8, 0x00A6, 0x00A9, 0x0080, 0x0088, 0x00B3, 0x0089, 0x00D5, 0x00D2, 0x00D3, 0x0000    };    // Touch screen to continue

const GFX_XCHAR cButtonStr[] = {   0x00B6, 0x00E8, 0x0000    };    // Buttons			

const GFX_XCHAR cCheckBoxStr[] = {   0x00A1, 0x00E4, 0x00C2, 0x0000    };    // Checkbox		

const GFX_XCHAR cRadioButtonStr[] = {   0x00DD, 0x0000    };    //Language	

const GFX_XCHAR cGroupBoxStr[] = {   0x00D0, 0x009B, 0x00C2, 0x0000    };    //GroupBox

const GFX_XCHAR cStaticTextStr[] = {   0x00EA, 0x00B2, 0x00B9, 0x00C0, 0x0000    };    //StaticText

const GFX_XCHAR cSliderStr[] = {   0x00C6, 0x0094, 0x00C1, 0x0000    };    //Slider			

const GFX_XCHAR cProgressBarStr[] = {   0x00E2, 0x00AD, 0x00C1, 0x0000    };    //Progress bar

const GFX_XCHAR cListBoxStr[] = {   0x0091, 0x00D9, 0x00C2, 0x0000    };    //List box		

const GFX_XCHAR cEditBoxStr[] = {   0x00D4, 0x00E0, 0x00C2, 0x0000    };    //Edit box		

const GFX_XCHAR cMeterStr[] = {   0x0087, 0x00D9, 0x0000    };    //Meter			

const GFX_XCHAR cDialStr[] = {   0x0087, 0x00D9, 0x00CD, 0x0000    };    //Dial			

const GFX_XCHAR cPictureStr[] = {   0x009F, 0x00C7, 0x0000    };    //Picture			

const GFX_XCHAR cCustomStr[] = {   0x00D7, 0x00A3, 0x0085, 0x00B7, 0x0092, 0x0000    };    //Custom Control	  

const GFX_XCHAR cSignatureStr[] = {   0x00CF, 0x009C, 0x0000    };    //Signature		

const GFX_XCHAR cPlottingStr[] = {   0x00D1, 0x009F, 0x0000    };    //Plotting		

const GFX_XCHAR cEcgStr[] = {   0x0045, 0x0043, 0x0047, 0x0000    };    //ECG 

const GFX_XCHAR cHomeStr[] = {   0x0084, 0x00EB, 0x0000    };    //Home			

const GFX_XCHAR cHomeLinesStr[] = {   0x0084, 0x00EB, 0x0031, 0x000A,
                                     0x0084, 0x00EB, 0x0032, 0x0000    };    //Home1/nHome2			

const GFX_XCHAR cLowStr[] = {   0x008A, 0x0000    };    //Low				

const GFX_XCHAR cHighStr[] = {   0x00EC, 0x0000    };    //High			

const GFX_XCHAR cOnStr[] = {   0x00AF, 0x0000    };    //On				

const GFX_XCHAR cOffStr[] = {   0x008E, 0x0000    };    //Off				

const GFX_XCHAR cEnableStr[] = {   0x008B, 0x00D6, 0x0000    };    //Enabled			

const GFX_XCHAR cDisabledStr[] = {   0x00CE, 0x00C3, 0x0000    };    //Disabled		

const GFX_XCHAR cTextLeftStr[] = {   0x00B9, 0x00C0, 0x00A8, 0x00E1, 0x0000    };    //Text Left						

const GFX_XCHAR cTextBottomStr[] = {   0x00B9, 0x00C0, 0x00AC, 0x00E7, 0x0000    };    //Text Bottom        				

const GFX_XCHAR cRb1Str[] = {   0x0052, 0x0062, 0x0031, 0x0000    };    //Rb1

const GFX_XCHAR cRb2Str[] = {   0x0052, 0x0062, 0x0032, 0x0000    };    //Rb2

const GFX_XCHAR cRb3Str[] = {   0x0052, 0x0062, 0x0033, 0x0000    };    //Rb3

const GFX_XCHAR cRb4Str[] = {   0x0045, 0x006E, 0x0067, 0x006C, 0x0069, 0x0073, 0x0068, 0x0000    };    //English

const GFX_XCHAR cRb5Str[] = {   0x0083, 0x00B9, 0x0000    };    //Chinese

const GFX_XCHAR cRb6Str[] = {   0x0052, 0x0062, 0x0036, 0x0000    };    //Rb6

const GFX_XCHAR cStaticTextLstStr[] = {   0x004D, 0x0069, 0x0063, 0x0072, 0x006F, 0x0063, 0x0068, 0x0069, 0x0070, 0x000A,
                                         0x009F, 0x00B0, 0x0095, 0x00AA, 0x00EA, 0x000A,
                                         0x00B2, 0x00B9, 0x00C0, 0x000A,
                                         0x009D, 0x00D0, 0x009B, 0x000A,
                                         0x00C2, 0x00C5, 0x00DC, 0x0000    };    //Microchip Graphics Library Static Text and Group Box Test.  

const GFX_XCHAR cLeftStr[] = {   0x00A8, 0x0000    };    //Left			

const GFX_XCHAR cCenterStr[] = {   0x0083, 0x0000    };    //Center			

const GFX_XCHAR cRightStr[] = {   0x0099, 0x0000    };    //Right			

const GFX_XCHAR cPIC24SpeedStr[] = {   0x0050, 0x0049, 0x0043, 0x00CC, 0x00BE, 0x00B1, 0x000A,
                                      0x00E6, 0x00AD, 0x00BC, 0x00A2, 0x00A5, 0x00ED, 0x0000    };    //How fast can PIC go?			 

const GFX_XCHAR cQuestionStr[] = {   0x003F, 0x0000    };    //? (Question mark)           

const GFX_XCHAR cSingleStr[] = {   0x0097, 0x0082, 0x0000    };    //Single			

const GFX_XCHAR cAlignCenterStr[] = {   0x0083, 0x00E9, 0x0000    };    //Center			

const GFX_XCHAR cListboxLstStr[] = {   0x00AB, 0x00C8, 0x000A,
                                      0x00A4, 0x00C9, 0x000A,
                                      0x00A4, 0x00AE, 0x00D7, 0x0094, 0x0095, 0x000A,
                                      0x00A7, 0x0081, 0x00B7, 0x0092, 0x000A,
                                      0x0096, 0x00CB, 0x00DB, 0x00A0, 0x000A,
                                      0x00C4, 0x00DF, 0x000A,
                                      0x0086, 0x0098, 0x00BD, 0x00A2, 0x007B, 0x0000    };    //Applications, Home Appliances, Home Automation, Industrial 		Controls, Medical Devices, Automotive and much more...

const GFX_XCHAR cCallingStr[] = {   0x00B4, 0x009A, 0x0083, 0x007B, 0x0000    };    //Calling...						

const GFX_XCHAR cHoldingStr[] = {   0x008C, 0x00B5, 0x00E5, 0x008D, 0x007B, 0x0000    };    //Holding...                      

const GFX_XCHAR cHoldStr[] = {   0x008C, 0x00B5, 0x0000    };    //Hold			

const GFX_XCHAR cAccelStr[] = {   0x0093, 0x00E6, 0x0000    };    //Accelerate (like increasing the speed)			

const GFX_XCHAR cDecelStr[] = {   0x008F, 0x00E6, 0x0000    };    //Decelerate (like decreasing the speed)			

const GFX_XCHAR cScaleStr[] = {   0x00D8, 0x009E, 0x0000    };    //Scale (like increase or decrease in size)		

const GFX_XCHAR cAnimateStr[] = {   0x0094, 0x00CA, 0x0000    };    //Animate (like a moving picture)

const GFX_XCHAR cLeftArrowStr[] = {   0x007E, 0x0020, 0x0000    };    // navigate left

const GFX_XCHAR cRightArrowStr[] = {   0x0020, 0x007F, 0x0000    };    // navigate right

const GFX_XCHAR cUpArrowStr[] = {   0x007C, 0x0000    };    // up arrow

const GFX_XCHAR cDownArrowStr[] = {   0x007D, 0x0000    };    // down arrow	

const GFX_XCHAR cExitStr[] = {   0x00E3, 0x0090, 0x0000    };    // exit			

const GFX_XCHAR cSetDateTimeStr[] = {   0x00DB, 0x00D5, 0x00BB, 0x00E9, 0x009D, 0x00BA, 0x00BF, 0x0000    };    //Set time and Date               

const GFX_XCHAR eTouchScreenStr[] = {   0x0054, 0x006F, 0x0075, 0x0063, 0x0068, 0x0020, 0x0073, 0x0063, 0x0072, 0x0065, 0x0065, 0x006E, 0x0020, 0x0074, 0x006F, 0x0020, 0x0063, 0x006F, 0x006E, 0x0074, 0x0069, 0x006E, 0x0075, 0x0065, 0x0000    };    //

const GFX_XCHAR eButtonStr[] = {   0x0042, 0x0075, 0x0074, 0x0074, 0x006F, 0x006E, 0x0073, 0x0000    };    //

const GFX_XCHAR eCheckBoxStr[] = {   0x0043, 0x0068, 0x0065, 0x0063, 0x006B, 0x0062, 0x006F, 0x0078, 0x0000    };    //

const GFX_XCHAR eRadioButtonStr[] = {   0x004C, 0x0061, 0x006E, 0x0067, 0x0075, 0x0061, 0x0067, 0x0065, 0x0000    };    //

const GFX_XCHAR eGroupBoxStr[] = {   0x0047, 0x0072, 0x006F, 0x0075, 0x0070, 0x0042, 0x006F, 0x0078, 0x0000    };    //

const GFX_XCHAR eStaticTextStr[] = {   0x0053, 0x0074, 0x0061, 0x0074, 0x0069, 0x0063, 0x0054, 0x0065, 0x0078, 0x0074, 0x0000    };    //

const GFX_XCHAR eSliderStr[] = {   0x0053, 0x006C, 0x0069, 0x0064, 0x0065, 0x0072, 0x0000    };    //

const GFX_XCHAR eProgressBarStr[] = {   0x0050, 0x0072, 0x006F, 0x0067, 0x0072, 0x0065, 0x0073, 0x0073, 0x0020, 0x0062, 0x0061, 0x0072, 0x0000    };    //

const GFX_XCHAR eListBoxStr[] = {   0x004C, 0x0069, 0x0073, 0x0074, 0x0020, 0x0062, 0x006F, 0x0078, 0x0000    };    //

const GFX_XCHAR eEditBoxStr[] = {   0x0045, 0x0064, 0x0069, 0x0074, 0x0020, 0x0062, 0x006F, 0x0078, 0x0000    };    //

const GFX_XCHAR eMeterStr[] = {   0x004D, 0x0065, 0x0074, 0x0065, 0x0072, 0x0000    };    //

const GFX_XCHAR eDialStr[] = {   0x0044, 0x0069, 0x0061, 0x006C, 0x0000    };    //

const GFX_XCHAR ePictureStr[] = {   0x0050, 0x0069, 0x0063, 0x0074, 0x0075, 0x0072, 0x0065, 0x0000    };    //

const GFX_XCHAR eCustomStr[] = {   0x0043, 0x0075, 0x0073, 0x0074, 0x006F, 0x006D, 0x0020, 0x0043, 0x006F, 0x006E, 0x0074, 0x0072, 0x006F, 0x006C, 0x0000    };    //

const GFX_XCHAR eSignatureStr[] = {   0x0053, 0x0069, 0x0067, 0x006E, 0x0061, 0x0074, 0x0075, 0x0072, 0x0065, 0x0000    };    //

const GFX_XCHAR ePlottingStr[] = {   0x0050, 0x006C, 0x006F, 0x0074, 0x0074, 0x0069, 0x006E, 0x0067, 0x0000    };    //

const GFX_XCHAR eEcgStr[] = {   0x0045, 0x0043, 0x0047, 0x0000    };    //

const GFX_XCHAR eHomeStr[] = {   0x0048, 0x006F, 0x006D, 0x0065, 0x0000    };    //

const GFX_XCHAR eHomeLinesStr[] = {   0x0048, 0x006F, 0x006D, 0x0065, 0x0031, 0x000A,
                                     0x0048, 0x006F, 0x006D, 0x0065, 0x0032, 0x0000    };    //

const GFX_XCHAR eLowStr[] = {   0x004C, 0x006F, 0x0077, 0x0000    };    //

const GFX_XCHAR eHighStr[] = {   0x0048, 0x0069, 0x0067, 0x0068, 0x0000    };    //

const GFX_XCHAR eOnStr[] = {   0x004F, 0x006E, 0x0000    };    //

const GFX_XCHAR eOffStr[] = {   0x004F, 0x0066, 0x0066, 0x0000    };    //

const GFX_XCHAR eEnableStr[] = {   0x0045, 0x006E, 0x0061, 0x0062, 0x006C, 0x0065, 0x0064, 0x0000    };    //

const GFX_XCHAR eDisabledStr[] = {   0x0044, 0x0069, 0x0073, 0x0061, 0x0062, 0x006C, 0x0065, 0x0064, 0x0000    };    //

const GFX_XCHAR eTextLeftStr[] = {   0x0054, 0x0065, 0x0078, 0x0074, 0x0020, 0x004C, 0x0065, 0x0066, 0x0074, 0x0000    };    //

const GFX_XCHAR eTextBottomStr[] = {   0x0054, 0x0065, 0x0078, 0x0074, 0x0020, 0x0042, 0x006F, 0x0074, 0x0074, 0x006F, 0x006D, 0x0000    };    //

const GFX_XCHAR eRb1Str[] = {   0x0052, 0x0062, 0x0031, 0x0000    };    //

const GFX_XCHAR eRb2Str[] = {   0x0052, 0x0062, 0x0032, 0x0000    };    //

const GFX_XCHAR eRb3Str[] = {   0x0052, 0x0062, 0x0033, 0x0000    };    //

const GFX_XCHAR eRb4Str[] = {   0x0045, 0x006E, 0x0067, 0x006C, 0x0069, 0x0073, 0x0068, 0x0000    };    //

const GFX_XCHAR eRb5Str[] = {   0x0083, 0x00B9, 0x0000    };    //

const GFX_XCHAR eRb6Str[] = {   0x0052, 0x0062, 0x0036, 0x0000    };    //

const GFX_XCHAR eStaticTextLstStr[] = {   0x004D, 0x0069, 0x0063, 0x0072, 0x006F, 0x0063, 0x0068, 0x0069, 0x0070, 0x000A,
                                         0x0047, 0x0072, 0x0061, 0x0070, 0x0068, 0x0069, 0x0063, 0x0073, 0x000A,
                                         0x004C, 0x0069, 0x0062, 0x0072, 0x0061, 0x0072, 0x0079, 0x000A,
                                         0x0053, 0x0074, 0x0061, 0x0074, 0x0069, 0x0063, 0x0020, 0x0054, 0x0065, 0x0078, 0x0074, 0x0020, 0x0026, 0x000A,
                                         0x0047, 0x0072, 0x006F, 0x0075, 0x0070, 0x0020, 0x0042, 0x006F, 0x0078, 0x0020, 0x0054, 0x0065, 0x0073, 0x0074, 0x0000    };    //

const GFX_XCHAR eLeftStr[] = {   0x004C, 0x0000    };    //

const GFX_XCHAR eCenterStr[] = {   0x0043, 0x0000    };    //   

const GFX_XCHAR eRightStr[] = {   0x0052, 0x0000    };    //

const GFX_XCHAR ePIC24SpeedStr[] = {   0x0048, 0x006F, 0x0077, 0x0020, 0x0066, 0x0061, 0x0073, 0x0074, 0x0020, 0x000A,
                                      0x0063, 0x0061, 0x006E, 0x0020, 0x0050, 0x0049, 0x0043, 0x0020, 0x0067, 0x006F, 0x003F, 0x0000    };    //

const GFX_XCHAR eQuestionStr[] = {   0x003F, 0x0000    };    //

const GFX_XCHAR eSingleStr[] = {   0x0053, 0x0069, 0x006E, 0x0067, 0x006C, 0x0065, 0x0000    };    //

const GFX_XCHAR eAlignCenterStr[] = {   0x0043, 0x0065, 0x006E, 0x0074, 0x0065, 0x0072, 0x0000    };    //

const GFX_XCHAR eListboxLstStr[] = {   0x0041, 0x0070, 0x0070, 0x006C, 0x0069, 0x0063, 0x0061, 0x0074, 0x0069, 0x006F, 0x006E, 0x0073, 0x0000,
                                      0x0048, 0x006F, 0x006D, 0x0065, 0x0020, 0x0041, 0x0070, 0x0070, 0x006C, 0x0069, 0x0061, 0x006E, 0x0063, 0x0065, 0x0073, 0x0000,
                                      0x0048, 0x006F, 0x006D, 0x0065, 0x0020, 0x0041, 0x0075, 0x0074, 0x006F, 0x006D, 0x0061, 0x0074, 0x0069, 0x006F, 0x006E, 0x0000,
                                      0x0049, 0x006E, 0x0064, 0x0075, 0x0073, 0x0074, 0x0072, 0x0069, 0x0061, 0x006C, 0x0020, 0x0043, 0x006F, 0x006E, 0x0074, 0x0072, 0x006F, 0x006C, 0x0073, 0x0000,
                                      0x004D, 0x0065, 0x0064, 0x0069, 0x0063, 0x0061, 0x006C, 0x0020, 0x0044, 0x0065, 0x0076, 0x0069, 0x0063, 0x0065, 0x0073, 0x0000,
                                      0x0041, 0x0075, 0x0074, 0x006F, 0x006D, 0x006F, 0x0074, 0x0069, 0x0076, 0x0065, 0x0000,
                                      0x0061, 0x006E, 0x0064, 0x0020, 0x006D, 0x0075, 0x0063, 0x0068, 0x0020, 0x006D, 0x006F, 0x0072, 0x0065, 0x002E, 0x002E, 0x002E, 0x0000, 0x0000    };    //

const GFX_XCHAR eCallingStr[] = {   0x0043, 0x0061, 0x006C, 0x006C, 0x0069, 0x006E, 0x0067, 0x002E, 0x002E, 0x002E, 0x0000    };    //

const GFX_XCHAR eHoldingStr[] = {   0x0048, 0x006F, 0x006C, 0x0064, 0x0069, 0x006E, 0x0067, 0x002E, 0x002E, 0x002E, 0x0000    };    //

const GFX_XCHAR eHoldStr[] = {   0x0048, 0x006F, 0x006C, 0x0064, 0x0000    };    //

const GFX_XCHAR eAccelStr[] = {   0x0041, 0x0063, 0x0063, 0x0065, 0x006C, 0x0000    };    //

const GFX_XCHAR eDecelStr[] = {   0x0044, 0x0063, 0x006C, 0x0072, 0x0074, 0x0000    };    //

const GFX_XCHAR eScaleStr[] = {   0x0053, 0x0063, 0x0061, 0x006C, 0x0065, 0x0000    };    //

const GFX_XCHAR eAnimateStr[] = {   0x0041, 0x006E, 0x0069, 0x006D, 0x0061, 0x0074, 0x0065, 0x0000    };    //

const GFX_XCHAR eLeftArrowStr[] = {   0x007E, 0x0020, 0x0000    };    // navigate left

const GFX_XCHAR eRightArrowStr[] = {   0x0020, 0x007F, 0x0000    };    // navigate right

const GFX_XCHAR eUpArrowStr[] = {   0x007C, 0x0000    };    // up arrow

const GFX_XCHAR eDownArrowStr[] = {   0x007D, 0x0000    };    // down arrow	

const GFX_XCHAR eExitStr[] = {   0x0045, 0x0078, 0x0069, 0x0074, 0x0000    };    //

const GFX_XCHAR eSetDateTimeStr[] = {   0x0053, 0x0065, 0x0074, 0x0020, 0x0054, 0x0069, 0x006D, 0x0065, 0x0020, 0x0061, 0x006E, 0x0064, 0x0020, 0x0044, 0x0061, 0x0074, 0x0065, 0x0000    };    //

/*****************************************************************************
 * SECTION:  GOLSmallFont - Unicode to GRC Index Table
 *****************************************************************************/

#ifdef GFX_LIB_CFG_USE_UNICODE_INDEX_TABLE
const uint16_t golsmallfontUnicodeIndexTable[155][2] =
{
//    Unicode   GRC Index
//    -------   ---------
    {  0x0020,   0x0020  },
    {  0x0021,   0x0021  },
    {  0x0022,   0x0022  },
    {  0x0023,   0x0023  },
    {  0x0024,   0x0024  },
    {  0x0025,   0x0025  },
    {  0x0026,   0x0026  },
    {  0x0027,   0x0027  },
    {  0x0028,   0x0028  },
    {  0x0029,   0x0029  },
    {  0x002A,   0x002A  },
    {  0x002B,   0x002B  },
    {  0x002C,   0x002C  },
    {  0x002D,   0x002D  },
    {  0x002E,   0x002E  },
    {  0x002F,   0x002F  },
    {  0x0030,   0x0030  },
    {  0x0031,   0x0031  },
    {  0x0032,   0x0032  },
    {  0x0033,   0x0033  },
    {  0x0034,   0x0034  },
    {  0x0035,   0x0035  },
    {  0x0036,   0x0036  },
    {  0x0037,   0x0037  },
    {  0x0038,   0x0038  },
    {  0x0039,   0x0039  },
    {  0x003A,   0x003A  },
    {  0x003B,   0x003B  },
    {  0x003C,   0x003C  },
    {  0x003D,   0x003D  },
    {  0x003E,   0x003E  },
    {  0x003F,   0x003F  },
    {  0x0040,   0x0040  },
    {  0x0041,   0x0041  },
    {  0x0042,   0x0042  },
    {  0x0043,   0x0043  },
    {  0x0044,   0x0044  },
    {  0x0045,   0x0045  },
    {  0x0046,   0x0046  },
    {  0x0047,   0x0047  },
    {  0x0048,   0x0048  },
    {  0x0049,   0x0049  },
    {  0x004A,   0x004A  },
    {  0x004B,   0x004B  },
    {  0x004C,   0x004C  },
    {  0x004D,   0x004D  },
    {  0x004E,   0x004E  },
    {  0x004F,   0x004F  },
    {  0x0050,   0x0050  },
    {  0x0051,   0x0051  },
    {  0x0052,   0x0052  },
    {  0x0053,   0x0053  },
    {  0x0054,   0x0054  },
    {  0x0055,   0x0055  },
    {  0x0056,   0x0056  },
    {  0x0057,   0x0057  },
    {  0x0058,   0x0058  },
    {  0x0059,   0x0059  },
    {  0x005A,   0x005A  },
    {  0x005B,   0x005B  },
    {  0x005C,   0x005C  },
    {  0x005D,   0x005D  },
    {  0x005E,   0x005E  },
    {  0x005F,   0x005F  },
    {  0x0060,   0x0060  },
    {  0x0061,   0x0061  },
    {  0x0062,   0x0062  },
    {  0x0063,   0x0063  },
    {  0x0064,   0x0064  },
    {  0x0065,   0x0065  },
    {  0x0066,   0x0066  },
    {  0x0067,   0x0067  },
    {  0x0068,   0x0068  },
    {  0x0069,   0x0069  },
    {  0x006A,   0x006A  },
    {  0x006B,   0x006B  },
    {  0x006C,   0x006C  },
    {  0x006D,   0x006D  },
    {  0x006E,   0x006E  },
    {  0x006F,   0x006F  },
    {  0x0070,   0x0070  },
    {  0x0071,   0x0071  },
    {  0x0072,   0x0072  },
    {  0x0073,   0x0073  },
    {  0x0074,   0x0074  },
    {  0x0075,   0x0075  },
    {  0x0076,   0x0076  },
    {  0x0077,   0x0077  },
    {  0x0078,   0x0078  },
    {  0x0079,   0x0079  },
    {  0x007A,   0x007A  },
    {  0x2026,   0x007B  },
    {  0x4E49,   0x007C  },
    {  0x4EEA,   0x007D  },
    {  0x4F4D,   0x007E  },
    {  0x4F7F,   0x007F  },
    {  0x5173,   0x0080  },
    {  0x5217,   0x0081  },
    {  0x5236,   0x0082  },
    {  0x52A8,   0x0083  },
    {  0x5355,   0x0084  },
    {  0x5408,   0x0085  },
    {  0x540D,   0x0086  },
    {  0x548C,   0x0087  },
    {  0x56DE,   0x0088  },
    {  0x56FE,   0x0089  },
    {  0x590D,   0x008A  },
    {  0x591A,   0x008B  },
    {  0x5B9A,   0x008C  },
    {  0x5BF9,   0x008D  },
    {  0x5E38,   0x008E  },
    {  0x5EA6,   0x008F  },
    {  0x5F00,   0x0090  },
    {  0x5F0F,   0x0091  },
    {  0x626B,   0x0092  },
    {  0x62E9,   0x0093  },
    {  0x6309,   0x0094  },
    {  0x63A7,   0x0095  },
    {  0x63CF,   0x0096  },
    {  0x6570,   0x0097  },
    {  0x65E5,   0x0098  },
    {  0x65F6,   0x0099  },
    {  0x66F4,   0x009A  },
    {  0x671F,   0x009B  },
    {  0x6761,   0x009C  },
    {  0x6846,   0x009D  },
    {  0x6A21,   0x009E  },
    {  0x6B63,   0x009F  },
    {  0x6EDA,   0x00A0  },
    {  0x7247,   0x00A1  },
    {  0x7528,   0x00A2  },
    {  0x7535,   0x00A3  },
    {  0x76D8,   0x00A4  },
    {  0x7B7E,   0x00A5  },
    {  0x7EC4,   0x00A6  },
    {  0x7ED8,   0x00A7  },
    {  0x7F16,   0x00A8  },
    {  0x7F6E,   0x00A9  },
    {  0x81EA,   0x00AA  },
    {  0x8868,   0x00AB  },
    {  0x8BA1,   0x00AC  },
    {  0x8BBE,   0x00AD  },
    {  0x8BFB,   0x00AE  },
    {  0x8D1F,   0x00AF  },
    {  0x8F7B,   0x00B0  },
    {  0x8F7D,   0x00B1  },
    {  0x8F83,   0x00B2  },
    {  0x8F91,   0x00B3  },
    {  0x8FD4,   0x00B4  },
    {  0x8FDB,   0x00B5  },
    {  0x9009,   0x00B6  },
    {  0x91CD,   0x00B7  },
    {  0x94AE,   0x00B8  },
    {  0x95F4,   0x00B9  },
    {  0x9F50,   0x00BA  },
};
#endif
/*****************************************************************************
 * SECTION:  GOLFontDefault - Unicode to GRC Index Table
 *****************************************************************************/

#ifdef GFX_LIB_CFG_USE_UNICODE_INDEX_TABLE
const uint16_t golfontdefaultUnicodeIndexTable[206][2] =
{
//    Unicode   GRC Index
//    -------   ---------
    {  0x0020,   0x0020  },
    {  0x0021,   0x0021  },
    {  0x0022,   0x0022  },
    {  0x0023,   0x0023  },
    {  0x0024,   0x0024  },
    {  0x0025,   0x0025  },
    {  0x0026,   0x0026  },
    {  0x0027,   0x0027  },
    {  0x0028,   0x0028  },
    {  0x0029,   0x0029  },
    {  0x002A,   0x002A  },
    {  0x002B,   0x002B  },
    {  0x002C,   0x002C  },
    {  0x002D,   0x002D  },
    {  0x002E,   0x002E  },
    {  0x002F,   0x002F  },
    {  0x0030,   0x0030  },
    {  0x0031,   0x0031  },
    {  0x0032,   0x0032  },
    {  0x0033,   0x0033  },
    {  0x0034,   0x0034  },
    {  0x0035,   0x0035  },
    {  0x0036,   0x0036  },
    {  0x0037,   0x0037  },
    {  0x0038,   0x0038  },
    {  0x0039,   0x0039  },
    {  0x003A,   0x003A  },
    {  0x003B,   0x003B  },
    {  0x003C,   0x003C  },
    {  0x003D,   0x003D  },
    {  0x003E,   0x003E  },
    {  0x003F,   0x003F  },
    {  0x0040,   0x0040  },
    {  0x0041,   0x0041  },
    {  0x0042,   0x0042  },
    {  0x0043,   0x0043  },
    {  0x0044,   0x0044  },
    {  0x0045,   0x0045  },
    {  0x0046,   0x0046  },
    {  0x0047,   0x0047  },
    {  0x0048,   0x0048  },
    {  0x0049,   0x0049  },
    {  0x004A,   0x004A  },
    {  0x004B,   0x004B  },
    {  0x004C,   0x004C  },
    {  0x004D,   0x004D  },
    {  0x004E,   0x004E  },
    {  0x004F,   0x004F  },
    {  0x0050,   0x0050  },
    {  0x0051,   0x0051  },
    {  0x0052,   0x0052  },
    {  0x0053,   0x0053  },
    {  0x0054,   0x0054  },
    {  0x0055,   0x0055  },
    {  0x0056,   0x0056  },
    {  0x0057,   0x0057  },
    {  0x0058,   0x0058  },
    {  0x0059,   0x0059  },
    {  0x005A,   0x005A  },
    {  0x005B,   0x005B  },
    {  0x005C,   0x005C  },
    {  0x005D,   0x005D  },
    {  0x005E,   0x005E  },
    {  0x005F,   0x005F  },
    {  0x0060,   0x0060  },
    {  0x0061,   0x0061  },
    {  0x0062,   0x0062  },
    {  0x0063,   0x0063  },
    {  0x0064,   0x0064  },
    {  0x0065,   0x0065  },
    {  0x0066,   0x0066  },
    {  0x0067,   0x0067  },
    {  0x0068,   0x0068  },
    {  0x0069,   0x0069  },
    {  0x006A,   0x006A  },
    {  0x006B,   0x006B  },
    {  0x006C,   0x006C  },
    {  0x006D,   0x006D  },
    {  0x006E,   0x006E  },
    {  0x006F,   0x006F  },
    {  0x0070,   0x0070  },
    {  0x0071,   0x0071  },
    {  0x0072,   0x0072  },
    {  0x0073,   0x0073  },
    {  0x0074,   0x0074  },
    {  0x0075,   0x0075  },
    {  0x0076,   0x0076  },
    {  0x0077,   0x0077  },
    {  0x0078,   0x0078  },
    {  0x0079,   0x0079  },
    {  0x007A,   0x007A  },
    {  0x2026,   0x007B  },
    {  0x2191,   0x007C  },
    {  0x2193,   0x007D  },
    {  0x300A,   0x007E  },
    {  0x300B,   0x007F  },
    {  0x4E0A,   0x0080  },
    {  0x4E1A,   0x0081  },
    {  0x4E2A,   0x0082  },
    {  0x4E2D,   0x0083  },
    {  0x4E3B,   0x0084  },
    {  0x4E49,   0x0085  },
    {  0x4EE5,   0x0086  },
    {  0x4EEA,   0x0087  },
    {  0x4EFB,   0x0088  },
    {  0x4F4D,   0x0089  },
    {  0x4F4E,   0x008A  },
    {  0x4F7F,   0x008B  },
    {  0x4FDD,   0x008C  },
    {  0x4FE1,   0x008D  },
    {  0x5173,   0x008E  },
    {  0x51CF,   0x008F  },
    {  0x51FA,   0x0090  },
    {  0x5217,   0x0091  },
    {  0x5236,   0x0092  },
    {  0x52A0,   0x0093  },
    {  0x52A8,   0x0094  },
    {  0x5316,   0x0095  },
    {  0x533B,   0x0096  },
    {  0x5355,   0x0097  },
    {  0x53CA,   0x0098  },
    {  0x53F3,   0x0099  },
    {  0x53F7,   0x009A  },
    {  0x5408,   0x009B  },
    {  0x540D,   0x009C  },
    {  0x548C,   0x009D  },
    {  0x56F4,   0x009E  },
    {  0x56FE,   0x009F  },
    {  0x5907,   0x00A0  },
    {  0x590D,   0x00A1  },
    {  0x591A,   0x00A2  },
    {  0x5B9A,   0x00A3  },
    {  0x5BB6,   0x00A4  },
    {  0x5C11,   0x00A5  },
    {  0x5C4F,   0x00A6  },
    {  0x5DE5,   0x00A7  },
    {  0x5DE6,   0x00A8  },
    {  0x5E55,   0x00A9  },
    {  0x5E93,   0x00AA  },
    {  0x5E94,   0x00AB  },
    {  0x5E95,   0x00AC  },
    {  0x5EA6,   0x00AD  },
    {  0x5EAD,   0x00AE  },
    {  0x5F00,   0x00AF  },
    {  0x5F62,   0x00B0  },
    {  0x5FEB,   0x00B1  },
    {  0x6001,   0x00B2  },
    {  0x610F,   0x00B3  },
    {  0x62E8,   0x00B4  },
    {  0x6301,   0x00B5  },
    {  0x6309,   0x00B6  },
    {  0x63A7,   0x00B7  },
    {  0x6478,   0x00B8  },
    {  0x6587,   0x00B9  },
    {  0x65E5,   0x00BA  },
    {  0x65F6,   0x00BB  },
    {  0x662F,   0x00BC  },
    {  0x66F4,   0x00BD  },
    {  0x6700,   0x00BE  },
    {  0x671F,   0x00BF  },
    {  0x672C,   0x00C0  },
    {  0x6761,   0x00C1  },
    {  0x6846,   0x00C2  },
    {  0x6B62,   0x00C3  },
    {  0x6C7D,   0x00C4  },
    {  0x6D4B,   0x00C5  },
    {  0x6EDA,   0x00C6  },
    {  0x7247,   0x00C7  },
    {  0x7528,   0x00C8  },
    {  0x7535,   0x00C9  },
    {  0x753B,   0x00CA  },
    {  0x7597,   0x00CB  },
    {  0x7684,   0x00CC  },
    {  0x76D8,   0x00CD  },
    {  0x7981,   0x00CE  },
    {  0x7B7E,   0x00CF  },
    {  0x7EC4,   0x00D0  },
    {  0x7ED8,   0x00D1  },
    {  0x7EE7,   0x00D2  },
    {  0x7EED,   0x00D3  },
    {  0x7F16,   0x00D4  },
    {  0x7F6E,   0x00D5  },
    {  0x80FD,   0x00D6  },
    {  0x81EA,   0x00D7  },
    {  0x8303,   0x00D8  },
    {  0x8868,   0x00D9  },
    {  0x89E6,   0x00DA  },
    {  0x8BBE,   0x00DB  },
    {  0x8BD5,   0x00DC  },
    {  0x8BED,   0x00DD  },
    {  0x8BF7,   0x00DE  },
    {  0x8F66,   0x00DF  },
    {  0x8F91,   0x00E0  },
    {  0x8FB9,   0x00E1  },
    {  0x8FDB,   0x00E2  },
    {  0x9000,   0x00E3  },
    {  0x9009,   0x00E4  },
    {  0x901A,   0x00E5  },
    {  0x901F,   0x00E6  },
    {  0x90E8,   0x00E7  },
    {  0x94AE,   0x00E8  },
    {  0x95F4,   0x00E9  },
    {  0x9759,   0x00EA  },
    {  0x9875,   0x00EB  },
    {  0x9AD8,   0x00EC  },
    {  0xFF1F,   0x00ED  },
};
#endif
/*****************************************************************************
 * SECTION:  BITMAPS
 *****************************************************************************/

/*********************************
 * Bitmap Structure
 * Label: Engine4
 * Description:  73x55 pixels, 4-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __Engine4[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __Engine4[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR Engine4 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_RLE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __Engine4,
    .resource.image.width = 73,
    .resource.image.height = 55,
    .resource.image.parameter1.compressedSize = 1930,
    .resource.image.parameter2.rawSize = 2068,
    .resource.image.colorDepth = 4,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: greenphone
 * Description:  48x35 pixels, 4-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __greenphone[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __greenphone[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR greenphone =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_RLE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __greenphone,
    .resource.image.width = 48,
    .resource.image.height = 35,
    .resource.image.parameter1.compressedSize = 633,
    .resource.image.parameter2.rawSize = 876,
    .resource.image.colorDepth = 4,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: intro
 * Description:  158x55 pixels, 8-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __intro[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __intro[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR intro =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_RLE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __intro,
    .resource.image.width = 158,
    .resource.image.height = 55,
    .resource.image.parameter1.compressedSize = 7417,
    .resource.image.parameter2.rawSize = 9204,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchpIcon
 * Description:  32x32 pixels, 1-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchpIcon[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchpIcon[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchpIcon =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchpIcon,
    .resource.image.width = 32,
    .resource.image.height = 32,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 136,
    .resource.image.colorDepth = 1,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchpLogo
 * Description:  152x40 pixels, 4-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchpLogo[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchpLogo[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchpLogo =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_RLE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchpLogo,
    .resource.image.width = 152,
    .resource.image.height = 40,
    .resource.image.parameter1.compressedSize = 1428,
    .resource.image.parameter2.rawSize = 3076,
    .resource.image.colorDepth = 4,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: arrowDown
 * Description:  18x26 pixels, 4-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __arrowDown[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __arrowDown[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR arrowDown =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __arrowDown,
    .resource.image.width = 18,
    .resource.image.height = 26,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 268,
    .resource.image.colorDepth = 4,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: arrowUp
 * Description:  18x26 pixels, 4-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __arrowUp[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __arrowUp[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR arrowUp =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __arrowUp,
    .resource.image.width = 18,
    .resource.image.height = 26,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 268,
    .resource.image.colorDepth = 4,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: bulboff
 * Description:  120x44 pixels, 4-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __bulboff[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __bulboff[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR bulboff =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_RLE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __bulboff,
    .resource.image.width = 120,
    .resource.image.height = 44,
    .resource.image.parameter1.compressedSize = 1161,
    .resource.image.parameter2.rawSize = 2676,
    .resource.image.colorDepth = 4,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: bulbon
 * Description:  120x44 pixels, 4-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __bulbon[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __bulbon[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR bulbon =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_RLE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __bulbon,
    .resource.image.width = 120,
    .resource.image.height = 44,
    .resource.image.parameter1.compressedSize = 1351,
    .resource.image.parameter2.rawSize = 2676,
    .resource.image.colorDepth = 4,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Engine1
 * Description:  73x55 pixels, 4-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __Engine1[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __Engine1[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR Engine1 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_RLE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __Engine1,
    .resource.image.width = 73,
    .resource.image.height = 55,
    .resource.image.parameter1.compressedSize = 1876,
    .resource.image.parameter2.rawSize = 2068,
    .resource.image.colorDepth = 4,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Engine2
 * Description:  73x55 pixels, 4-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __Engine2[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __Engine2[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR Engine2 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_RLE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __Engine2,
    .resource.image.width = 73,
    .resource.image.height = 55,
    .resource.image.parameter1.compressedSize = 1876,
    .resource.image.parameter2.rawSize = 2068,
    .resource.image.colorDepth = 4,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Engine3
 * Description:  73x55 pixels, 4-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __Engine3[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __Engine3[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR Engine3 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_RLE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __Engine3,
    .resource.image.width = 73,
    .resource.image.height = 55,
    .resource.image.parameter1.compressedSize = 1895,
    .resource.image.parameter2.rawSize = 2068,
    .resource.image.colorDepth = 4,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: redphone
 * Description:  48x35 pixels, 4-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __redphone[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __redphone[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR redphone =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_RLE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __redphone,
    .resource.image.width = 48,
    .resource.image.height = 35,
    .resource.image.parameter1.compressedSize = 710,
    .resource.image.parameter2.rawSize = 876,
    .resource.image.colorDepth = 4,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchpIcon0
 * Description:  32x32 pixels, 1-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchpIcon0[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchpIcon0[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchpIcon0 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchpIcon0,
    .resource.image.width = 32,
    .resource.image.height = 32,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 136,
    .resource.image.colorDepth = 1,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*****************************************************************************
 * SECTION:  FONTS
 *****************************************************************************/

/*********************************
 * TTF Font File Structure
 * Label: monofont
 * Description:  Height: 20 pixels, 1 bit per pixel, Range: '.' to '9'
 * Comment Block:
 * Created from Bitstream Vera Fonts 
 *  
 * Copyright (c) 2003, Bitstream Inc. 
 * All Rights Reserved. Bitstream 
 * Vera is a trademark of Bitstream, Inc. 
 *  
 * Permission is hereby granted, free of charge, to any person obtaining 
 * a copy of the fonts accompanying this license ("Fonts") and associated 
 * documentation files (the "Font Software"), to reproduce and distribute 
 * the Font Software, including without limitation the rights to use, 
 * copy, merge, publish, distribute, and/or sell copies of the Font 
 * Software, and to permit persons to whom the Font Software is furnished 
 * to do so, subject to the following conditions: 
 *  
 * The above copyright and trademark notices and this permission notice 
 * shall be included in all copies of one or more of the Font Software 
 * typefaces. 
 *  
 * The Font Software may be modified, altered, or added to, and in 
 * particular the designs of glyphs or characters in the Fonts may be 
 * modified and additional glyphs or characters may be added to the 
 * Fonts, only if the fonts are renamed to names not containing either 
 * the words "Bitstream" or the word "Vera". 
 *  
 * This License becomes null and void to the extent applicable to Fonts 
 * or Font Software that has been modified and is distributed under the 
 * "Bitstream Vera" names. 
 *  
 * The Font Software may be sold as part of a larger software package but 
 * no copy of one or more of the Font Software typefaces may be sold by 
 * itself. 
 * 
 * THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF 
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT 
 * OF COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL 
 * BITSTREAM OR THE GNOME FOUNDATION BE LIABLE FOR ANY CLAIM, DAMAGES OR 
 * OTHER LIABILITY, INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, 
 * OR CONSEQUENTIAL DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR 
 * OTHERWISE, ARISING FROM, OUT OF THE USE OR INABILITY TO USE THE FONT 
 * SOFTWARE OR FROM OTHER DEALINGS IN THE FONT SOFTWARE. 
 *  
 * Except as contained in this notice, the names of Gnome, the Gnome 
 * Foundation, and Bitstream Inc., shall not be used in advertising or 
 * otherwise to promote the sale, use or other dealings in this Font 
 * Software without prior written authorization from the Gnome Foundation 
 * or Bitstream Inc., respectively. For further information, contact: 
 * fonts at gnome dot org. 
 *  
 ***********************************/
#if defined(GFX_CONFIG_FONT_PROG_SPACE_ENABLE) && (__XC16_VERSION__ >= 1011)
#ifndef GFX_CONFIG_FONT_PACKED_ENABLE
extern GFX_FONT_SPACE char __monofont[] __attribute__((section("grc_text"), aligned(2)));
#else
extern GFX_FONT_SPACE char __monofont[] __attribute__((section("grc_text")));
#endif
#else
extern GFX_FONT_SPACE char __monofont[] __attribute__((aligned(2)));
#endif

const GFX_RESOURCE_HDR monofont = 
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0000,
    .resource.font.location.progByteAddress = (GFX_FONT_SPACE char *) __monofont,
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x002E,
    .resource.font.header.lastChar = 0x0039,
    .resource.font.header.height = 0x0014,
};
/*********************************
 * TTF Font File Structure
 * Label: GOLSmallFont
 * Description:  Height: 15 pixels, 1 bit per pixel, Range: ' ' to '?'
 * Comment Block:
 * ========================================================================== 
 *  
 * Created from AR PL New Sung font (fireflysung.ttf). 
 *  
 * AR PL New Sung font is 
 *     Copyright (c) 1994-1999, Arphic Technology Co., Ltd. 
 *     Copyright (C) 1999-2004, Firefly and Arphic Technology Co., Ltd. 
 * All Rights Reserved. 
 *  
 * NOTICE: This Truetype font contains embedded bitmap fonts made 
 *     by firefly and is released as a whole 
 *     under the ARPHIC PUBLIC LICENSE. 
 *     There are also seperate bitmap fonts made by Firefly and 
 *     released under the GENERAL PUBLIC LICENSE (GPL): 
 *     http://www.study-area.org/apt/firefly-font/bitmaps/ 
 *  
 * Copyright: 
 *     (Copied from 'license/english/ARPHICPL.TXT'. 
 *     See 'license/big5/ARPHICPL.TXT' or 'license/gb/ARPHICPL.TXT' 
 *     for the Chinese version.) 
 *  
 * ========================================================================== 
 *  
 * ARPHIC PUBLIC LICENSE 
 *  
 * Copyright (C) 1999 Arphic Technology Co., Ltd. 
 * 11Fl. No.168, Yung Chi Rd., Taipei, 110 Taiwan 
 * All rights reserved except as specified below. 
 *  
 * Everyone is permitted to copy and distribute verbatim copies of this 
 * license document, but changing it is forbidden. 
 *  
 * Preamble 
 *  
 *    The licenses for most software are designed to take away your freedom 
 * to share and change it. By contrast, the ARPHIC PUBLIC LICENSE 
 * specifically permits and encourages you to use this software, provided 
 * that you give the recipients all the rights that we gave you and make 
 * sure they can get the modifications of this software. 
 *  
 * Legal Terms 
 *  
 * 0. Definitions: 
 *    Throughout this License, "Font" means the TrueType fonts "AR PL 
 * Mingti2L Big5", "AR PL KaitiM Big5" (BIG-5 character set) and "AR PL 
 * SungtiL GB", "AR PL KaitiM GB" (GB character set) which are originally 
 * distributed by Arphic, and the derivatives of those fonts created 
 * through any modification including modifying glyph, reordering glyph, 
 * converting format, changing font name, or adding/deleting some 
 * characters in/from glyph table. 
 *  
 *    "PL" means "Public License". 
 *  
 *    "Copyright Holder" means whoever is named in the copyright or 
 * copyrights for the Font. 
 *  
 *    "You" means the licensee, or person copying, redistributing or 
 * modifying the Font. 
 *  
 *    "Freely Available" means that you have the freedom to copy or modify 
 * the Font as well as redistribute copies of the Font under the same 
 * conditions you received, not price. If you wish, you can charge for this 
 * service. 
 *  
 * 1. Copying & Distribution 
 *    You may copy and distribute verbatim copies of this Font in any 
 * medium, without restriction, provided that you retain this license file 
 * (ARPHICPL.TXT) unaltered in all copies. 
 *  
 * 2. Modification 
 *    You may otherwise modify your copy of this Font in any way, including 
 * modifying glyph, reordering glyph, converting format, changing font 
 * name, or adding/deleting some characters in/from glyph table, and copy 
 * and distribute such modifications under the terms of Section 1 above, 
 * provided that the following conditions are met: 
 *  
 *    a) You must insert a prominent notice in each modified file stating 
 * how and when you changed that file. 
 *  
 *    b) You must make such modifications Freely Available as a whole to 
 * all third parties under the terms of this License, such as by offering 
 * access to copy the modifications from a designated place, or 
 * distributing the modifications on a medium customarily used for software 
 * interchange. 
 *  
 *    c) If the modified fonts normally reads commands interactively when 
 * run, you must cause it, when started running for such interactive use in 
 * the most ordinary way, to print or display an announcement including an 
 * appropriate copyright notice and a notice that there is no warranty (or 
 * else, saying that you provide a warranty) and that users may 
 * redistribute the Font under these conditions, and telling the user how 
 * to view a copy of this License. 
 *  
 *    These requirements apply to the modified work as a whole. If 
 * identifiable sections of that work are not derived from the Font, and 
 * can be reasonably considered independent and separate works in 
 * themselves, then this License and its terms, do not apply to those 
 * sections when you distribute them as separate works. Therefore, mere 
 * aggregation of another work not based on the Font with the Font on a 
 * volume of a storage or distribution medium does not bring the other work 
 * under the scope of this License. 
 *  
 * 3. Condition Subsequent 
 *    You may not copy, modify, sublicense, or distribute the Font except 
 * as expressly provided under this License. Any attempt otherwise to copy, 
 * modify, sublicense or distribute the Font will automatically 
 * retroactively void your rights under this License. However, parties who 
 * have received copies or rights from you under this License will keep 
 * their licenses valid so long as such parties remain in full compliance. 
 *  
 * 4. Acceptance 
 *    You are not required to accept this License, since you have not 
 * signed it. However, nothing else grants you permission to copy, modify, 
 * sublicense or distribute the Font. These actions are prohibited by law 
 * if you do not accept this License. Therefore, by copying, modifying, 
 * sublicensing or distributing the Font, you indicate your acceptance of 
 * this License and all its terms and conditions. 
 *  
 * 5. Automatic Receipt 
 *    Each time you redistribute the Font, the recipient automatically 
 * receives a license from the original licensor to copy, distribute or 
 * modify the Font subject to these terms and conditions. You may not 
 * impose any further restrictions on the recipients' exercise of the 
 * rights granted herein. You are not responsible for enforcing compliance 
 * by third parties to this License. 
 *  
 * 6. Contradiction 
 *    If, as a consequence of a court judgment or allegation of patent 
 * infringement or for any other reason (not limited to patent issues), 
 * conditions are imposed on you (whether by court order, agreement or 
 * otherwise) that contradict the conditions of this License, they do not 
 * excuse you from the conditions of this License. If you cannot distribute 
 * so as to satisfy simultaneously your obligations under this License and 
 * any other pertinent obligations, then as a consequence you may not 
 * distribute the Font at all. For example, if a patent license would not 
 * permit royalty-free redistribution of the Font by all those who receive 
 * copies directly or indirectly through you, then the only way you could 
 * satisfy both it and this License would be to refrain entirely from 
 * distribution of the Font. 
 *  
 *    If any portion of this section is held invalid or unenforceable under 
 * any particular circumstance, the balance of the section is intended to 
 * apply and the section as a whole is intended to apply in other 
 * circumstances. 
 *  
 * 7. NO WARRANTY 
 *    BECAUSE THE FONT IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY FOR 
 * THE FONT, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN 
 * OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS OR OTHER PARTIES 
 * PROVIDE THE FONT "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED 
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS 
 * TO THE QUALITY AND PERFORMANCE OF THE FONT IS WITH YOU. SHOULD THE FONT 
 * PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR 
 * OR CORRECTION. 
 *  
 * 8. DAMAGES WAIVER 
 *    UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, IN NO 
 * EVENT WILL ANY COPYRIGHTT HOLDERS, OR OTHER PARTIES WHO MAY COPY, MODIFY 
 * OR REDISTRIBUTE THE FONT AS PERMITTED ABOVE, BE LIABLE TO YOU FOR ANY 
 * DIRECT, INDIRECT, CONSEQUENTIAL, INCIDENTAL, SPECIAL OR EXEMPLARY 
 * DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE FONT (INCLUDING 
 * BUT NOT LIMITED TO PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF 
 * USE, DATA OR PROFITS; OR BUSINESS INTERRUPTION), EVEN IF SUCH HOLDERS OR 
 * OTHER PARTIES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. 
 *  
 * ====================================================================== 
 ***********************************/
#if defined(GFX_CONFIG_FONT_PROG_SPACE_ENABLE) && (__XC16_VERSION__ >= 1011)
#ifndef GFX_CONFIG_FONT_PACKED_ENABLE
extern GFX_FONT_SPACE char __GOLSmallFont[] __attribute__((section("grc_text"), aligned(2)));
#else
extern GFX_FONT_SPACE char __GOLSmallFont[] __attribute__((section("grc_text")));
#endif
#else
extern GFX_FONT_SPACE char __GOLSmallFont[] __attribute__((aligned(2)));
#endif

const GFX_RESOURCE_HDR GOLSmallFont = 
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0000,
    .resource.font.location.progByteAddress = (GFX_FONT_SPACE char *) __GOLSmallFont,
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x0020,
    .resource.font.header.lastChar = 0x00BA,
    .resource.font.header.height = 0x000F,
};
/*********************************
 * TTF Font File Structure
 * Label: GOLFontDefault
 * Description:  Height: 17 pixels, 1 bit per pixel, Range: ' ' to '?'
 * Comment Block:
 * ========================================================================== 
 *  
 * Created from AR PL New Sung font (fireflysung.ttf). 
 *  
 * AR PL New Sung font is 
 *     Copyright (c) 1994-1999, Arphic Technology Co., Ltd. 
 *     Copyright (C) 1999-2004, Firefly and Arphic Technology Co., Ltd. 
 * All Rights Reserved. 
 *  
 * NOTICE: This Truetype font contains embedded bitmap fonts made 
 *     by firefly and is released as a whole 
 *     under the ARPHIC PUBLIC LICENSE. 
 *     There are also seperate bitmap fonts made by Firefly and 
 *     released under the GENERAL PUBLIC LICENSE (GPL): 
 *     http://www.study-area.org/apt/firefly-font/bitmaps/ 
 *  
 * Copyright: 
 *     (Copied from 'license/english/ARPHICPL.TXT'. 
 *     See 'license/big5/ARPHICPL.TXT' or 'license/gb/ARPHICPL.TXT' 
 *     for the Chinese version.) 
 *  
 * ========================================================================== 
 *  
 * ARPHIC PUBLIC LICENSE 
 *  
 * Copyright (C) 1999 Arphic Technology Co., Ltd. 
 * 11Fl. No.168, Yung Chi Rd., Taipei, 110 Taiwan 
 * All rights reserved except as specified below. 
 *  
 * Everyone is permitted to copy and distribute verbatim copies of this 
 * license document, but changing it is forbidden. 
 *  
 * Preamble 
 *  
 *    The licenses for most software are designed to take away your freedom 
 * to share and change it. By contrast, the ARPHIC PUBLIC LICENSE 
 * specifically permits and encourages you to use this software, provided 
 * that you give the recipients all the rights that we gave you and make 
 * sure they can get the modifications of this software. 
 *  
 * Legal Terms 
 *  
 * 0. Definitions: 
 *    Throughout this License, "Font" means the TrueType fonts "AR PL 
 * Mingti2L Big5", "AR PL KaitiM Big5" (BIG-5 character set) and "AR PL 
 * SungtiL GB", "AR PL KaitiM GB" (GB character set) which are originally 
 * distributed by Arphic, and the derivatives of those fonts created 
 * through any modification including modifying glyph, reordering glyph, 
 * converting format, changing font name, or adding/deleting some 
 * characters in/from glyph table. 
 *  
 *    "PL" means "Public License". 
 *  
 *    "Copyright Holder" means whoever is named in the copyright or 
 * copyrights for the Font. 
 *  
 *    "You" means the licensee, or person copying, redistributing or 
 * modifying the Font. 
 *  
 *    "Freely Available" means that you have the freedom to copy or modify 
 * the Font as well as redistribute copies of the Font under the same 
 * conditions you received, not price. If you wish, you can charge for this 
 * service. 
 *  
 * 1. Copying & Distribution 
 *    You may copy and distribute verbatim copies of this Font in any 
 * medium, without restriction, provided that you retain this license file 
 * (ARPHICPL.TXT) unaltered in all copies. 
 *  
 * 2. Modification 
 *    You may otherwise modify your copy of this Font in any way, including 
 * modifying glyph, reordering glyph, converting format, changing font 
 * name, or adding/deleting some characters in/from glyph table, and copy 
 * and distribute such modifications under the terms of Section 1 above, 
 * provided that the following conditions are met: 
 *  
 *    a) You must insert a prominent notice in each modified file stating 
 * how and when you changed that file. 
 *  
 *    b) You must make such modifications Freely Available as a whole to 
 * all third parties under the terms of this License, such as by offering 
 * access to copy the modifications from a designated place, or 
 * distributing the modifications on a medium customarily used for software 
 * interchange. 
 *  
 *    c) If the modified fonts normally reads commands interactively when 
 * run, you must cause it, when started running for such interactive use in 
 * the most ordinary way, to print or display an announcement including an 
 * appropriate copyright notice and a notice that there is no warranty (or 
 * else, saying that you provide a warranty) and that users may 
 * redistribute the Font under these conditions, and telling the user how 
 * to view a copy of this License. 
 *  
 *    These requirements apply to the modified work as a whole. If 
 * identifiable sections of that work are not derived from the Font, and 
 * can be reasonably considered independent and separate works in 
 * themselves, then this License and its terms, do not apply to those 
 * sections when you distribute them as separate works. Therefore, mere 
 * aggregation of another work not based on the Font with the Font on a 
 * volume of a storage or distribution medium does not bring the other work 
 * under the scope of this License. 
 *  
 * 3. Condition Subsequent 
 *    You may not copy, modify, sublicense, or distribute the Font except 
 * as expressly provided under this License. Any attempt otherwise to copy, 
 * modify, sublicense or distribute the Font will automatically 
 * retroactively void your rights under this License. However, parties who 
 * have received copies or rights from you under this License will keep 
 * their licenses valid so long as such parties remain in full compliance. 
 *  
 * 4. Acceptance 
 *    You are not required to accept this License, since you have not 
 * signed it. However, nothing else grants you permission to copy, modify, 
 * sublicense or distribute the Font. These actions are prohibited by law 
 * if you do not accept this License. Therefore, by copying, modifying, 
 * sublicensing or distributing the Font, you indicate your acceptance of 
 * this License and all its terms and conditions. 
 *  
 * 5. Automatic Receipt 
 *    Each time you redistribute the Font, the recipient automatically 
 * receives a license from the original licensor to copy, distribute or 
 * modify the Font subject to these terms and conditions. You may not 
 * impose any further restrictions on the recipients' exercise of the 
 * rights granted herein. You are not responsible for enforcing compliance 
 * by third parties to this License. 
 *  
 * 6. Contradiction 
 *    If, as a consequence of a court judgment or allegation of patent 
 * infringement or for any other reason (not limited to patent issues), 
 * conditions are imposed on you (whether by court order, agreement or 
 * otherwise) that contradict the conditions of this License, they do not 
 * excuse you from the conditions of this License. If you cannot distribute 
 * so as to satisfy simultaneously your obligations under this License and 
 * any other pertinent obligations, then as a consequence you may not 
 * distribute the Font at all. For example, if a patent license would not 
 * permit royalty-free redistribution of the Font by all those who receive 
 * copies directly or indirectly through you, then the only way you could 
 * satisfy both it and this License would be to refrain entirely from 
 * distribution of the Font. 
 *  
 *    If any portion of this section is held invalid or unenforceable under 
 * any particular circumstance, the balance of the section is intended to 
 * apply and the section as a whole is intended to apply in other 
 * circumstances. 
 *  
 * 7. NO WARRANTY 
 *    BECAUSE THE FONT IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY FOR 
 * THE FONT, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN 
 * OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS OR OTHER PARTIES 
 * PROVIDE THE FONT "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED 
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS 
 * TO THE QUALITY AND PERFORMANCE OF THE FONT IS WITH YOU. SHOULD THE FONT 
 * PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR 
 * OR CORRECTION. 
 *  
 * 8. DAMAGES WAIVER 
 *    UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, IN NO 
 * EVENT WILL ANY COPYRIGHTT HOLDERS, OR OTHER PARTIES WHO MAY COPY, MODIFY 
 * OR REDISTRIBUTE THE FONT AS PERMITTED ABOVE, BE LIABLE TO YOU FOR ANY 
 * DIRECT, INDIRECT, CONSEQUENTIAL, INCIDENTAL, SPECIAL OR EXEMPLARY 
 * DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE FONT (INCLUDING 
 * BUT NOT LIMITED TO PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF 
 * USE, DATA OR PROFITS; OR BUSINESS INTERRUPTION), EVEN IF SUCH HOLDERS OR 
 * OTHER PARTIES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. 
 *  
 * ====================================================================== 
 ***********************************/
#if defined(GFX_CONFIG_FONT_PROG_SPACE_ENABLE) && (__XC16_VERSION__ >= 1011)
#ifndef GFX_CONFIG_FONT_PACKED_ENABLE
extern GFX_FONT_SPACE char __GOLFontDefault[] __attribute__((section("grc_text"), aligned(2)));
#else
extern GFX_FONT_SPACE char __GOLFontDefault[] __attribute__((section("grc_text")));
#endif
#else
extern GFX_FONT_SPACE char __GOLFontDefault[] __attribute__((aligned(2)));
#endif

const GFX_RESOURCE_HDR GOLFontDefault = 
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0000,
    .resource.font.location.progByteAddress = (GFX_FONT_SPACE char *) __GOLFontDefault,
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x0020,
    .resource.font.header.lastChar = 0x00ED,
    .resource.font.header.height = 0x0011,
};
