/*****************************************************************************
  AUTO-GENERATED CODE:  Graphics Resource Converter version: 4.00.39 BETA

  Company:
      Microchip Technology, Inc.
 
  File Name:
     internal_resource.h
 
  Summary:
      This file is generated by the Microchip's Graphics Resource Converter.
  Description:
      This file is generated by the Graphics Resource Converter containing
      resources such as images and fonts that can be used by Microchip's
      Graphics Library, which is part of the MLA.
 *****************************************************************************/

// DOM-IGNORE-BEGIN
/*****************************************************************************
  Software License Agreement

  Copyright(c) 2013 Microchip Technology Inc.  All rights reserved.
  Microchip licenses to you the right to use, modify, copy and distribute
  Software only when embedded on a Microchip microcontroller or digital
  signal controller that is integrated into your product or third party
  product (pursuant to the sublicense terms in the accompanying license
  agreement).
 
  You should refer to the license agreement accompanying this Software
  for additional information regarding your rights and obligations.
 
  SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY
  KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
  OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
  PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
  OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
  BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
  DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
  INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
  COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
  CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
  OR OTHER SIMILAR COSTS.
 *****************************************************************************/
// DOM-IGNORE-END

#ifndef INTERNAL_RESOURCE_H_FILE
#define INTERNAL_RESOURCE_H_FILE
/*****************************************************************************
 * SECTION:  Includes
 *****************************************************************************/
#include <gfx/gfx.h>
#include <stdint.h>

/*****************************************************************************
 * SECTION:  Graphics Library Firmware Check
 *****************************************************************************/
#if(GRAPHICS_LIBRARY_VERSION != 0x0400)
#warning "It is suggested to use Graphics Library version 4.00 with this version of GRC."
#endif

/*****************************************************************************
 * SECTION:  Graphics Bitmap Padding Check
 *****************************************************************************/
#ifdef GFX_CONFIG_IMAGE_PADDING_DISABLE
#error These bitmap resources have been converted with padding of the horizontal lines, but GFX_CONFIG_IMAGE_PADDING_DISABLE is defined in system_config.h.
#endif


/*****************************************************************************
 * SECTION: Graphics Configuration
 * Overview:    This defines the size of the buffer used by font functions
 *              to retrieve font data from the external memory. The buffer
 *              size can be increased to accommodate large font sizes.
 *              The user must be aware of the expected glyph sizes of the 
 *              characters stored in the font table. 
 *              To modify the size used, declare this macro in the 
 *              GraphicsConfig.h file with the desired size.
 *
 * #define GFX_EXTERNAL_FONT_RASTER_BUFFER_SIZE     (40)
 *****************************************************************************/

/*****************************************************************************
 * This is an error check for the color depth
 *****************************************************************************/
#if (COLOR_DEPTH > 16)
#error "Color Depth needs to be 16 to correctly use these resources"
#endif



/*****************************************************************************
 * SECTION:  BITMAPS
 *****************************************************************************/

/*********************************
 * Bitmap Structure
 * Label: Engine4
 * Description:  73x55 pixels, 4-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR Engine4;
#define Engine4_WIDTH     (73)
#define Engine4_HEIGHT    (55)
#define Engine4_SIZE      (2073)
/*********************************
 * Bitmap Structure
 * Label: greenphone
 * Description:  48x35 pixels, 4-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR greenphone;
#define greenphone_WIDTH     (48)
#define greenphone_HEIGHT    (35)
#define greenphone_SIZE      (878)
/*********************************
 * Bitmap Structure
 * Label: intro
 * Description:  158x55 pixels, 8-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR intro;
#define intro_WIDTH     (158)
#define intro_HEIGHT    (55)
#define intro_SIZE      (9208)
/*********************************
 * Bitmap Structure
 * Label: mchpIcon
 * Description:  32x32 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchpIcon;
#define mchpIcon_WIDTH     (32)
#define mchpIcon_HEIGHT    (32)
#define mchpIcon_SIZE      (138)
/*********************************
 * Bitmap Structure
 * Label: mchpLogo
 * Description:  152x40 pixels, 4-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchpLogo;
#define mchpLogo_WIDTH     (152)
#define mchpLogo_HEIGHT    (40)
#define mchpLogo_SIZE      (3078)
/*********************************
 * Bitmap Structure
 * Label: arrowDown
 * Description:  18x26 pixels, 4-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR arrowDown;
#define arrowDown_WIDTH     (18)
#define arrowDown_HEIGHT    (26)
#define arrowDown_SIZE      (272)
/*********************************
 * Bitmap Structure
 * Label: arrowUp
 * Description:  18x26 pixels, 4-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR arrowUp;
#define arrowUp_WIDTH     (18)
#define arrowUp_HEIGHT    (26)
#define arrowUp_SIZE      (272)
/*********************************
 * Bitmap Structure
 * Label: bulboff
 * Description:  120x44 pixels, 4-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR bulboff;
#define bulboff_WIDTH     (120)
#define bulboff_HEIGHT    (44)
#define bulboff_SIZE      (2678)
/*********************************
 * Bitmap Structure
 * Label: bulbon
 * Description:  120x44 pixels, 4-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR bulbon;
#define bulbon_WIDTH     (120)
#define bulbon_HEIGHT    (44)
#define bulbon_SIZE      (2678)
/*********************************
 * Bitmap Structure
 * Label: Engine1
 * Description:  73x55 pixels, 4-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR Engine1;
#define Engine1_WIDTH     (73)
#define Engine1_HEIGHT    (55)
#define Engine1_SIZE      (2073)
/*********************************
 * Bitmap Structure
 * Label: Engine2
 * Description:  73x55 pixels, 4-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR Engine2;
#define Engine2_WIDTH     (73)
#define Engine2_HEIGHT    (55)
#define Engine2_SIZE      (2073)
/*********************************
 * Bitmap Structure
 * Label: Engine3
 * Description:  73x55 pixels, 4-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR Engine3;
#define Engine3_WIDTH     (73)
#define Engine3_HEIGHT    (55)
#define Engine3_SIZE      (2073)
/*********************************
 * Bitmap Structure
 * Label: redphone
 * Description:  48x35 pixels, 4-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR redphone;
#define redphone_WIDTH     (48)
#define redphone_HEIGHT    (35)
#define redphone_SIZE      (878)
/*********************************
 * Bitmap Structure
 * Label: mchpIcon0
 * Description:  32x32 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchpIcon0;
#define mchpIcon0_WIDTH     (32)
#define mchpIcon0_HEIGHT    (32)
#define mchpIcon0_SIZE      (138)
/*****************************************************************************
 * SECTION:  Fonts
 *****************************************************************************/

/*********************************
 * TTF Font File Structure
 * Label: monofont
 * Description:  Height: 20 pixels, 1 bit per pixel, Range: '.' to '9'
 * Comment Block:
 * Created from Bitstream Vera Fonts 
 *  
 * Copyright (c) 2003, Bitstream Inc. 
 * All Rights Reserved. Bitstream 
 * Vera is a trademark of Bitstream, Inc. 
 *  
 * Permission is hereby granted, free of charge, to any person obtaining 
 * a copy of the fonts accompanying this license ("Fonts") and associated 
 * documentation files (the "Font Software"), to reproduce and distribute 
 * the Font Software, including without limitation the rights to use, 
 * copy, merge, publish, distribute, and/or sell copies of the Font 
 * Software, and to permit persons to whom the Font Software is furnished 
 * to do so, subject to the following conditions: 
 *  
 * The above copyright and trademark notices and this permission notice 
 * shall be included in all copies of one or more of the Font Software 
 * typefaces. 
 *  
 * The Font Software may be modified, altered, or added to, and in 
 * particular the designs of glyphs or characters in the Fonts may be 
 * modified and additional glyphs or characters may be added to the 
 * Fonts, only if the fonts are renamed to names not containing either 
 * the words "Bitstream" or the word "Vera". 
 *  
 * This License becomes null and void to the extent applicable to Fonts 
 * or Font Software that has been modified and is distributed under the 
 * "Bitstream Vera" names. 
 *  
 * The Font Software may be sold as part of a larger software package but 
 * no copy of one or more of the Font Software typefaces may be sold by 
 * itself. 
 * 
 * THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF 
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT 
 * OF COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL 
 * BITSTREAM OR THE GNOME FOUNDATION BE LIABLE FOR ANY CLAIM, DAMAGES OR 
 * OTHER LIABILITY, INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, 
 * OR CONSEQUENTIAL DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR 
 * OTHERWISE, ARISING FROM, OUT OF THE USE OR INABILITY TO USE THE FONT 
 * SOFTWARE OR FROM OTHER DEALINGS IN THE FONT SOFTWARE. 
 *  
 * Except as contained in this notice, the names of Gnome, the Gnome 
 * Foundation, and Bitstream Inc., shall not be used in advertising or 
 * otherwise to promote the sale, use or other dealings in this Font 
 * Software without prior written authorization from the Gnome Foundation 
 * or Bitstream Inc., respectively. For further information, contact: 
 * fonts at gnome dot org. 
 *  
 ***********************************/
extern const GFX_RESOURCE_HDR monofont;
#define monofont_SIZE    (536)
/*********************************
 * TTF Font File Structure
 * Label: GOLSmallFont
 * Description:  Height: 15 pixels, 1 bit per pixel, Range: ' ' to '?'
 * Comment Block:
 * ========================================================================== 
 *  
 * Created from AR PL New Sung font (fireflysung.ttf). 
 *  
 * AR PL New Sung font is 
 *     Copyright (c) 1994-1999, Arphic Technology Co., Ltd. 
 *     Copyright (C) 1999-2004, Firefly and Arphic Technology Co., Ltd. 
 * All Rights Reserved. 
 *  
 * NOTICE: This Truetype font contains embedded bitmap fonts made 
 *     by firefly and is released as a whole 
 *     under the ARPHIC PUBLIC LICENSE. 
 *     There are also seperate bitmap fonts made by Firefly and 
 *     released under the GENERAL PUBLIC LICENSE (GPL): 
 *     http://www.study-area.org/apt/firefly-font/bitmaps/ 
 *  
 * Copyright: 
 *     (Copied from 'license/english/ARPHICPL.TXT'. 
 *     See 'license/big5/ARPHICPL.TXT' or 'license/gb/ARPHICPL.TXT' 
 *     for the Chinese version.) 
 *  
 * ========================================================================== 
 *  
 * ARPHIC PUBLIC LICENSE 
 *  
 * Copyright (C) 1999 Arphic Technology Co., Ltd. 
 * 11Fl. No.168, Yung Chi Rd., Taipei, 110 Taiwan 
 * All rights reserved except as specified below. 
 *  
 * Everyone is permitted to copy and distribute verbatim copies of this 
 * license document, but changing it is forbidden. 
 *  
 * Preamble 
 *  
 *    The licenses for most software are designed to take away your freedom 
 * to share and change it. By contrast, the ARPHIC PUBLIC LICENSE 
 * specifically permits and encourages you to use this software, provided 
 * that you give the recipients all the rights that we gave you and make 
 * sure they can get the modifications of this software. 
 *  
 * Legal Terms 
 *  
 * 0. Definitions: 
 *    Throughout this License, "Font" means the TrueType fonts "AR PL 
 * Mingti2L Big5", "AR PL KaitiM Big5" (BIG-5 character set) and "AR PL 
 * SungtiL GB", "AR PL KaitiM GB" (GB character set) which are originally 
 * distributed by Arphic, and the derivatives of those fonts created 
 * through any modification including modifying glyph, reordering glyph, 
 * converting format, changing font name, or adding/deleting some 
 * characters in/from glyph table. 
 *  
 *    "PL" means "Public License". 
 *  
 *    "Copyright Holder" means whoever is named in the copyright or 
 * copyrights for the Font. 
 *  
 *    "You" means the licensee, or person copying, redistributing or 
 * modifying the Font. 
 *  
 *    "Freely Available" means that you have the freedom to copy or modify 
 * the Font as well as redistribute copies of the Font under the same 
 * conditions you received, not price. If you wish, you can charge for this 
 * service. 
 *  
 * 1. Copying & Distribution 
 *    You may copy and distribute verbatim copies of this Font in any 
 * medium, without restriction, provided that you retain this license file 
 * (ARPHICPL.TXT) unaltered in all copies. 
 *  
 * 2. Modification 
 *    You may otherwise modify your copy of this Font in any way, including 
 * modifying glyph, reordering glyph, converting format, changing font 
 * name, or adding/deleting some characters in/from glyph table, and copy 
 * and distribute such modifications under the terms of Section 1 above, 
 * provided that the following conditions are met: 
 *  
 *    a) You must insert a prominent notice in each modified file stating 
 * how and when you changed that file. 
 *  
 *    b) You must make such modifications Freely Available as a whole to 
 * all third parties under the terms of this License, such as by offering 
 * access to copy the modifications from a designated place, or 
 * distributing the modifications on a medium customarily used for software 
 * interchange. 
 *  
 *    c) If the modified fonts normally reads commands interactively when 
 * run, you must cause it, when started running for such interactive use in 
 * the most ordinary way, to print or display an announcement including an 
 * appropriate copyright notice and a notice that there is no warranty (or 
 * else, saying that you provide a warranty) and that users may 
 * redistribute the Font under these conditions, and telling the user how 
 * to view a copy of this License. 
 *  
 *    These requirements apply to the modified work as a whole. If 
 * identifiable sections of that work are not derived from the Font, and 
 * can be reasonably considered independent and separate works in 
 * themselves, then this License and its terms, do not apply to those 
 * sections when you distribute them as separate works. Therefore, mere 
 * aggregation of another work not based on the Font with the Font on a 
 * volume of a storage or distribution medium does not bring the other work 
 * under the scope of this License. 
 *  
 * 3. Condition Subsequent 
 *    You may not copy, modify, sublicense, or distribute the Font except 
 * as expressly provided under this License. Any attempt otherwise to copy, 
 * modify, sublicense or distribute the Font will automatically 
 * retroactively void your rights under this License. However, parties who 
 * have received copies or rights from you under this License will keep 
 * their licenses valid so long as such parties remain in full compliance. 
 *  
 * 4. Acceptance 
 *    You are not required to accept this License, since you have not 
 * signed it. However, nothing else grants you permission to copy, modify, 
 * sublicense or distribute the Font. These actions are prohibited by law 
 * if you do not accept this License. Therefore, by copying, modifying, 
 * sublicensing or distributing the Font, you indicate your acceptance of 
 * this License and all its terms and conditions. 
 *  
 * 5. Automatic Receipt 
 *    Each time you redistribute the Font, the recipient automatically 
 * receives a license from the original licensor to copy, distribute or 
 * modify the Font subject to these terms and conditions. You may not 
 * impose any further restrictions on the recipients' exercise of the 
 * rights granted herein. You are not responsible for enforcing compliance 
 * by third parties to this License. 
 *  
 * 6. Contradiction 
 *    If, as a consequence of a court judgment or allegation of patent 
 * infringement or for any other reason (not limited to patent issues), 
 * conditions are imposed on you (whether by court order, agreement or 
 * otherwise) that contradict the conditions of this License, they do not 
 * excuse you from the conditions of this License. If you cannot distribute 
 * so as to satisfy simultaneously your obligations under this License and 
 * any other pertinent obligations, then as a consequence you may not 
 * distribute the Font at all. For example, if a patent license would not 
 * permit royalty-free redistribution of the Font by all those who receive 
 * copies directly or indirectly through you, then the only way you could 
 * satisfy both it and this License would be to refrain entirely from 
 * distribution of the Font. 
 *  
 *    If any portion of this section is held invalid or unenforceable under 
 * any particular circumstance, the balance of the section is intended to 
 * apply and the section as a whole is intended to apply in other 
 * circumstances. 
 *  
 * 7. NO WARRANTY 
 *    BECAUSE THE FONT IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY FOR 
 * THE FONT, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN 
 * OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS OR OTHER PARTIES 
 * PROVIDE THE FONT "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED 
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS 
 * TO THE QUALITY AND PERFORMANCE OF THE FONT IS WITH YOU. SHOULD THE FONT 
 * PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR 
 * OR CORRECTION. 
 *  
 * 8. DAMAGES WAIVER 
 *    UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, IN NO 
 * EVENT WILL ANY COPYRIGHTT HOLDERS, OR OTHER PARTIES WHO MAY COPY, MODIFY 
 * OR REDISTRIBUTE THE FONT AS PERMITTED ABOVE, BE LIABLE TO YOU FOR ANY 
 * DIRECT, INDIRECT, CONSEQUENTIAL, INCIDENTAL, SPECIAL OR EXEMPLARY 
 * DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE FONT (INCLUDING 
 * BUT NOT LIMITED TO PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF 
 * USE, DATA OR PROFITS; OR BUSINESS INTERRUPTION), EVEN IF SUCH HOLDERS OR 
 * OTHER PARTIES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. 
 *  
 * ====================================================================== 
 ***********************************/
extern const GFX_RESOURCE_HDR GOLSmallFont;
#define GOLSmallFont_SIZE    (3913)
/*********************************
 * TTF Font File Structure
 * Label: GOLFontDefault
 * Description:  Height: 17 pixels, 1 bit per pixel, Range: ' ' to '?'
 * Comment Block:
 * ========================================================================== 
 *  
 * Created from AR PL New Sung font (fireflysung.ttf). 
 *  
 * AR PL New Sung font is 
 *     Copyright (c) 1994-1999, Arphic Technology Co., Ltd. 
 *     Copyright (C) 1999-2004, Firefly and Arphic Technology Co., Ltd. 
 * All Rights Reserved. 
 *  
 * NOTICE: This Truetype font contains embedded bitmap fonts made 
 *     by firefly and is released as a whole 
 *     under the ARPHIC PUBLIC LICENSE. 
 *     There are also seperate bitmap fonts made by Firefly and 
 *     released under the GENERAL PUBLIC LICENSE (GPL): 
 *     http://www.study-area.org/apt/firefly-font/bitmaps/ 
 *  
 * Copyright: 
 *     (Copied from 'license/english/ARPHICPL.TXT'. 
 *     See 'license/big5/ARPHICPL.TXT' or 'license/gb/ARPHICPL.TXT' 
 *     for the Chinese version.) 
 *  
 * ========================================================================== 
 *  
 * ARPHIC PUBLIC LICENSE 
 *  
 * Copyright (C) 1999 Arphic Technology Co., Ltd. 
 * 11Fl. No.168, Yung Chi Rd., Taipei, 110 Taiwan 
 * All rights reserved except as specified below. 
 *  
 * Everyone is permitted to copy and distribute verbatim copies of this 
 * license document, but changing it is forbidden. 
 *  
 * Preamble 
 *  
 *    The licenses for most software are designed to take away your freedom 
 * to share and change it. By contrast, the ARPHIC PUBLIC LICENSE 
 * specifically permits and encourages you to use this software, provided 
 * that you give the recipients all the rights that we gave you and make 
 * sure they can get the modifications of this software. 
 *  
 * Legal Terms 
 *  
 * 0. Definitions: 
 *    Throughout this License, "Font" means the TrueType fonts "AR PL 
 * Mingti2L Big5", "AR PL KaitiM Big5" (BIG-5 character set) and "AR PL 
 * SungtiL GB", "AR PL KaitiM GB" (GB character set) which are originally 
 * distributed by Arphic, and the derivatives of those fonts created 
 * through any modification including modifying glyph, reordering glyph, 
 * converting format, changing font name, or adding/deleting some 
 * characters in/from glyph table. 
 *  
 *    "PL" means "Public License". 
 *  
 *    "Copyright Holder" means whoever is named in the copyright or 
 * copyrights for the Font. 
 *  
 *    "You" means the licensee, or person copying, redistributing or 
 * modifying the Font. 
 *  
 *    "Freely Available" means that you have the freedom to copy or modify 
 * the Font as well as redistribute copies of the Font under the same 
 * conditions you received, not price. If you wish, you can charge for this 
 * service. 
 *  
 * 1. Copying & Distribution 
 *    You may copy and distribute verbatim copies of this Font in any 
 * medium, without restriction, provided that you retain this license file 
 * (ARPHICPL.TXT) unaltered in all copies. 
 *  
 * 2. Modification 
 *    You may otherwise modify your copy of this Font in any way, including 
 * modifying glyph, reordering glyph, converting format, changing font 
 * name, or adding/deleting some characters in/from glyph table, and copy 
 * and distribute such modifications under the terms of Section 1 above, 
 * provided that the following conditions are met: 
 *  
 *    a) You must insert a prominent notice in each modified file stating 
 * how and when you changed that file. 
 *  
 *    b) You must make such modifications Freely Available as a whole to 
 * all third parties under the terms of this License, such as by offering 
 * access to copy the modifications from a designated place, or 
 * distributing the modifications on a medium customarily used for software 
 * interchange. 
 *  
 *    c) If the modified fonts normally reads commands interactively when 
 * run, you must cause it, when started running for such interactive use in 
 * the most ordinary way, to print or display an announcement including an 
 * appropriate copyright notice and a notice that there is no warranty (or 
 * else, saying that you provide a warranty) and that users may 
 * redistribute the Font under these conditions, and telling the user how 
 * to view a copy of this License. 
 *  
 *    These requirements apply to the modified work as a whole. If 
 * identifiable sections of that work are not derived from the Font, and 
 * can be reasonably considered independent and separate works in 
 * themselves, then this License and its terms, do not apply to those 
 * sections when you distribute them as separate works. Therefore, mere 
 * aggregation of another work not based on the Font with the Font on a 
 * volume of a storage or distribution medium does not bring the other work 
 * under the scope of this License. 
 *  
 * 3. Condition Subsequent 
 *    You may not copy, modify, sublicense, or distribute the Font except 
 * as expressly provided under this License. Any attempt otherwise to copy, 
 * modify, sublicense or distribute the Font will automatically 
 * retroactively void your rights under this License. However, parties who 
 * have received copies or rights from you under this License will keep 
 * their licenses valid so long as such parties remain in full compliance. 
 *  
 * 4. Acceptance 
 *    You are not required to accept this License, since you have not 
 * signed it. However, nothing else grants you permission to copy, modify, 
 * sublicense or distribute the Font. These actions are prohibited by law 
 * if you do not accept this License. Therefore, by copying, modifying, 
 * sublicensing or distributing the Font, you indicate your acceptance of 
 * this License and all its terms and conditions. 
 *  
 * 5. Automatic Receipt 
 *    Each time you redistribute the Font, the recipient automatically 
 * receives a license from the original licensor to copy, distribute or 
 * modify the Font subject to these terms and conditions. You may not 
 * impose any further restrictions on the recipients' exercise of the 
 * rights granted herein. You are not responsible for enforcing compliance 
 * by third parties to this License. 
 *  
 * 6. Contradiction 
 *    If, as a consequence of a court judgment or allegation of patent 
 * infringement or for any other reason (not limited to patent issues), 
 * conditions are imposed on you (whether by court order, agreement or 
 * otherwise) that contradict the conditions of this License, they do not 
 * excuse you from the conditions of this License. If you cannot distribute 
 * so as to satisfy simultaneously your obligations under this License and 
 * any other pertinent obligations, then as a consequence you may not 
 * distribute the Font at all. For example, if a patent license would not 
 * permit royalty-free redistribution of the Font by all those who receive 
 * copies directly or indirectly through you, then the only way you could 
 * satisfy both it and this License would be to refrain entirely from 
 * distribution of the Font. 
 *  
 *    If any portion of this section is held invalid or unenforceable under 
 * any particular circumstance, the balance of the section is intended to 
 * apply and the section as a whole is intended to apply in other 
 * circumstances. 
 *  
 * 7. NO WARRANTY 
 *    BECAUSE THE FONT IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY FOR 
 * THE FONT, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN 
 * OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS OR OTHER PARTIES 
 * PROVIDE THE FONT "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED 
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS 
 * TO THE QUALITY AND PERFORMANCE OF THE FONT IS WITH YOU. SHOULD THE FONT 
 * PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR 
 * OR CORRECTION. 
 *  
 * 8. DAMAGES WAIVER 
 *    UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, IN NO 
 * EVENT WILL ANY COPYRIGHTT HOLDERS, OR OTHER PARTIES WHO MAY COPY, MODIFY 
 * OR REDISTRIBUTE THE FONT AS PERMITTED ABOVE, BE LIABLE TO YOU FOR ANY 
 * DIRECT, INDIRECT, CONSEQUENTIAL, INCIDENTAL, SPECIAL OR EXEMPLARY 
 * DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE FONT (INCLUDING 
 * BUT NOT LIMITED TO PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF 
 * USE, DATA OR PROFITS; OR BUSINESS INTERRUPTION), EVEN IF SUCH HOLDERS OR 
 * OTHER PARTIES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. 
 *  
 * ====================================================================== 
 ***********************************/
extern const GFX_RESOURCE_HDR GOLFontDefault;
#define GOLFontDefault_SIZE    (6289)
/*****************************************************************************
 * SECTION:  GOLSmallFont
 *****************************************************************************/

extern const GFX_XCHAR cOnBulbStr[];
extern const GFX_XCHAR cOffBulbStr[];
extern const GFX_XCHAR cSelectionStr[];
extern const GFX_XCHAR cAlignmentStr[];
extern const GFX_XCHAR cReturnStr[];
extern const GFX_XCHAR cMeter1Str[];
extern const GFX_XCHAR cMeter2Str[];
extern const GFX_XCHAR cValueLabelStr[];
extern const GFX_XCHAR cMoreStr[];
extern const GFX_XCHAR cBackStr[];
extern const GFX_XCHAR cGroup1Str[];
extern const GFX_XCHAR cGroup2Str[];
extern const GFX_XCHAR cSetTimeDateStr[];
extern const GFX_XCHAR cNormalLoadStr[];
extern const GFX_XCHAR cLightLoadStr[];
extern const GFX_XCHAR cHeavyLoadStr[];
extern const GFX_XCHAR cUseR6PotStr[];
extern const GFX_XCHAR cScanModeStr[];
extern const GFX_XCHAR cScrSelList1[];
extern const GFX_XCHAR cScrSelList2[];
extern const GFX_XCHAR cScrSelListLang[];
extern const GFX_XCHAR cLanguage[];
extern const GFX_XCHAR eOnBulbStr[];
extern const GFX_XCHAR eOffBulbStr[];
extern const GFX_XCHAR eSelectionStr[];
extern const GFX_XCHAR eAlignmentStr[];
extern const GFX_XCHAR eReturnStr[];
extern const GFX_XCHAR eMeter1Str[];
extern const GFX_XCHAR eMeter2Str[];
extern const GFX_XCHAR eValueLabelStr[];
extern const GFX_XCHAR eMoreStr[];
extern const GFX_XCHAR eBackStr[];
extern const GFX_XCHAR eGroup1Str[];
extern const GFX_XCHAR eGroup2Str[];
extern const GFX_XCHAR eSetTimeDateStr[];
extern const GFX_XCHAR eNormalLoadStr[];
extern const GFX_XCHAR eLightLoadStr[];
extern const GFX_XCHAR eHeavyLoadStr[];
extern const GFX_XCHAR eUseR6PotStr[];
extern const GFX_XCHAR eScanModeStr[];
extern const GFX_XCHAR eScrSelList1[];
extern const GFX_XCHAR eScrSelList2[];
extern const GFX_XCHAR eScrSelListLang[];
extern const GFX_XCHAR eLanguage[];
/*****************************************************************************
 * SECTION:  GOLFontDefault
 *****************************************************************************/

extern const GFX_XCHAR cTouchScreenStr[];
extern const GFX_XCHAR cButtonStr[];
extern const GFX_XCHAR cCheckBoxStr[];
extern const GFX_XCHAR cRadioButtonStr[];
extern const GFX_XCHAR cGroupBoxStr[];
extern const GFX_XCHAR cStaticTextStr[];
extern const GFX_XCHAR cSliderStr[];
extern const GFX_XCHAR cProgressBarStr[];
extern const GFX_XCHAR cListBoxStr[];
extern const GFX_XCHAR cEditBoxStr[];
extern const GFX_XCHAR cMeterStr[];
extern const GFX_XCHAR cDialStr[];
extern const GFX_XCHAR cPictureStr[];
extern const GFX_XCHAR cCustomStr[];
extern const GFX_XCHAR cSignatureStr[];
extern const GFX_XCHAR cPlottingStr[];
extern const GFX_XCHAR cEcgStr[];
extern const GFX_XCHAR cHomeStr[];
extern const GFX_XCHAR cHomeLinesStr[];
extern const GFX_XCHAR cLowStr[];
extern const GFX_XCHAR cHighStr[];
extern const GFX_XCHAR cOnStr[];
extern const GFX_XCHAR cOffStr[];
extern const GFX_XCHAR cEnableStr[];
extern const GFX_XCHAR cDisabledStr[];
extern const GFX_XCHAR cTextLeftStr[];
extern const GFX_XCHAR cTextBottomStr[];
extern const GFX_XCHAR cRb1Str[];
extern const GFX_XCHAR cRb2Str[];
extern const GFX_XCHAR cRb3Str[];
extern const GFX_XCHAR cRb4Str[];
extern const GFX_XCHAR cRb5Str[];
extern const GFX_XCHAR cRb6Str[];
extern const GFX_XCHAR cStaticTextLstStr[];
extern const GFX_XCHAR cLeftStr[];
extern const GFX_XCHAR cCenterStr[];
extern const GFX_XCHAR cRightStr[];
extern const GFX_XCHAR cPIC24SpeedStr[];
extern const GFX_XCHAR cQuestionStr[];
extern const GFX_XCHAR cSingleStr[];
extern const GFX_XCHAR cAlignCenterStr[];
extern const GFX_XCHAR cListboxLstStr[];
extern const GFX_XCHAR cCallingStr[];
extern const GFX_XCHAR cHoldingStr[];
extern const GFX_XCHAR cHoldStr[];
extern const GFX_XCHAR cAccelStr[];
extern const GFX_XCHAR cDecelStr[];
extern const GFX_XCHAR cScaleStr[];
extern const GFX_XCHAR cAnimateStr[];
extern const GFX_XCHAR cLeftArrowStr[];
extern const GFX_XCHAR cRightArrowStr[];
extern const GFX_XCHAR cUpArrowStr[];
extern const GFX_XCHAR cDownArrowStr[];
extern const GFX_XCHAR cExitStr[];
extern const GFX_XCHAR cSetDateTimeStr[];
extern const GFX_XCHAR eTouchScreenStr[];
extern const GFX_XCHAR eButtonStr[];
extern const GFX_XCHAR eCheckBoxStr[];
extern const GFX_XCHAR eRadioButtonStr[];
extern const GFX_XCHAR eGroupBoxStr[];
extern const GFX_XCHAR eStaticTextStr[];
extern const GFX_XCHAR eSliderStr[];
extern const GFX_XCHAR eProgressBarStr[];
extern const GFX_XCHAR eListBoxStr[];
extern const GFX_XCHAR eEditBoxStr[];
extern const GFX_XCHAR eMeterStr[];
extern const GFX_XCHAR eDialStr[];
extern const GFX_XCHAR ePictureStr[];
extern const GFX_XCHAR eCustomStr[];
extern const GFX_XCHAR eSignatureStr[];
extern const GFX_XCHAR ePlottingStr[];
extern const GFX_XCHAR eEcgStr[];
extern const GFX_XCHAR eHomeStr[];
extern const GFX_XCHAR eHomeLinesStr[];
extern const GFX_XCHAR eLowStr[];
extern const GFX_XCHAR eHighStr[];
extern const GFX_XCHAR eOnStr[];
extern const GFX_XCHAR eOffStr[];
extern const GFX_XCHAR eEnableStr[];
extern const GFX_XCHAR eDisabledStr[];
extern const GFX_XCHAR eTextLeftStr[];
extern const GFX_XCHAR eTextBottomStr[];
extern const GFX_XCHAR eRb1Str[];
extern const GFX_XCHAR eRb2Str[];
extern const GFX_XCHAR eRb3Str[];
extern const GFX_XCHAR eRb4Str[];
extern const GFX_XCHAR eRb5Str[];
extern const GFX_XCHAR eRb6Str[];
extern const GFX_XCHAR eStaticTextLstStr[];
extern const GFX_XCHAR eLeftStr[];
extern const GFX_XCHAR eCenterStr[];
extern const GFX_XCHAR eRightStr[];
extern const GFX_XCHAR ePIC24SpeedStr[];
extern const GFX_XCHAR eQuestionStr[];
extern const GFX_XCHAR eSingleStr[];
extern const GFX_XCHAR eAlignCenterStr[];
extern const GFX_XCHAR eListboxLstStr[];
extern const GFX_XCHAR eCallingStr[];
extern const GFX_XCHAR eHoldingStr[];
extern const GFX_XCHAR eHoldStr[];
extern const GFX_XCHAR eAccelStr[];
extern const GFX_XCHAR eDecelStr[];
extern const GFX_XCHAR eScaleStr[];
extern const GFX_XCHAR eAnimateStr[];
extern const GFX_XCHAR eLeftArrowStr[];
extern const GFX_XCHAR eRightArrowStr[];
extern const GFX_XCHAR eUpArrowStr[];
extern const GFX_XCHAR eDownArrowStr[];
extern const GFX_XCHAR eExitStr[];
extern const GFX_XCHAR eSetDateTimeStr[];
#endif

